<?php
/**
 * AnnulationDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * AnnulationDto Class Doc Comment
 *
 * @category Class
 * @description Formulaire de demande d&#39;annulation
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AnnulationDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AnnulationDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'codeEnvoi' => 'string',
        'requestId' => 'string',
        'numeroExpediteur' => 'string',
        'indicatifExpediteur' => 'string',
        'adresseIP' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'codeEnvoi' => null,
        'requestId' => null,
        'numeroExpediteur' => null,
        'indicatifExpediteur' => null,
        'adresseIP' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'codeEnvoi' => false,
        'requestId' => false,
        'numeroExpediteur' => false,
        'indicatifExpediteur' => false,
        'adresseIP' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'codeEnvoi' => 'codeEnvoi',
        'requestId' => 'requestId',
        'numeroExpediteur' => 'numeroExpediteur',
        'indicatifExpediteur' => 'indicatifExpediteur',
        'adresseIP' => 'adresseIP'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'codeEnvoi' => 'setCodeEnvoi',
        'requestId' => 'setRequestId',
        'numeroExpediteur' => 'setNumeroExpediteur',
        'indicatifExpediteur' => 'setIndicatifExpediteur',
        'adresseIP' => 'setAdresseIP'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'codeEnvoi' => 'getCodeEnvoi',
        'requestId' => 'getRequestId',
        'numeroExpediteur' => 'getNumeroExpediteur',
        'indicatifExpediteur' => 'getIndicatifExpediteur',
        'adresseIP' => 'getAdresseIP'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('codeEnvoi', $data ?? [], null);
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('numeroExpediteur', $data ?? [], null);
        $this->setIfExists('indicatifExpediteur', $data ?? [], null);
        $this->setIfExists('adresseIP', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['codeEnvoi'] === null) {
            $invalidProperties[] = "'codeEnvoi' can't be null";
        }
        if ((mb_strlen($this->container['codeEnvoi']) > 50)) {
            $invalidProperties[] = "invalid value for 'codeEnvoi', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['codeEnvoi']) < 0)) {
            $invalidProperties[] = "invalid value for 'codeEnvoi', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['requestId'] === null) {
            $invalidProperties[] = "'requestId' can't be null";
        }
        if ((mb_strlen($this->container['requestId']) > 100)) {
            $invalidProperties[] = "invalid value for 'requestId', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['requestId']) < 0)) {
            $invalidProperties[] = "invalid value for 'requestId', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['numeroExpediteur'] === null) {
            $invalidProperties[] = "'numeroExpediteur' can't be null";
        }
        if ((mb_strlen($this->container['numeroExpediteur']) < 1)) {
            $invalidProperties[] = "invalid value for 'numeroExpediteur', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\d{4,15}$/", $this->container['numeroExpediteur'])) {
            $invalidProperties[] = "invalid value for 'numeroExpediteur', must be conform to the pattern /^\\d{4,15}$/.";
        }

        if ($this->container['indicatifExpediteur'] === null) {
            $invalidProperties[] = "'indicatifExpediteur' can't be null";
        }
        if ((mb_strlen($this->container['indicatifExpediteur']) < 1)) {
            $invalidProperties[] = "invalid value for 'indicatifExpediteur', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\+?\\d{2,6}$/", $this->container['indicatifExpediteur'])) {
            $invalidProperties[] = "invalid value for 'indicatifExpediteur', must be conform to the pattern /^\\+?\\d{2,6}$/.";
        }

        if (!is_null($this->container['adresseIP']) && (mb_strlen($this->container['adresseIP']) > 45)) {
            $invalidProperties[] = "invalid value for 'adresseIP', the character length must be smaller than or equal to 45.";
        }

        if (!is_null($this->container['adresseIP']) && (mb_strlen($this->container['adresseIP']) < 0)) {
            $invalidProperties[] = "invalid value for 'adresseIP', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets codeEnvoi
     *
     * @return string
     */
    public function getCodeEnvoi()
    {
        return $this->container['codeEnvoi'];
    }

    /**
     * Sets codeEnvoi
     *
     * @param string $codeEnvoi codeEnvoi
     *
     * @return self
     */
    public function setCodeEnvoi($codeEnvoi)
    {
        if (is_null($codeEnvoi)) {
            throw new \InvalidArgumentException('non-nullable codeEnvoi cannot be null');
        }
        if ((mb_strlen($codeEnvoi) > 50)) {
            throw new \InvalidArgumentException('invalid length for $codeEnvoi when calling AnnulationDto., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($codeEnvoi) < 0)) {
            throw new \InvalidArgumentException('invalid length for $codeEnvoi when calling AnnulationDto., must be bigger than or equal to 0.');
        }

        $this->container['codeEnvoi'] = $codeEnvoi;

        return $this;
    }

    /**
     * Gets requestId
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string $requestId requestId
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }
        if ((mb_strlen($requestId) > 100)) {
            throw new \InvalidArgumentException('invalid length for $requestId when calling AnnulationDto., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($requestId) < 0)) {
            throw new \InvalidArgumentException('invalid length for $requestId when calling AnnulationDto., must be bigger than or equal to 0.');
        }

        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets numeroExpediteur
     *
     * @return string
     */
    public function getNumeroExpediteur()
    {
        return $this->container['numeroExpediteur'];
    }

    /**
     * Sets numeroExpediteur
     *
     * @param string $numeroExpediteur numeroExpediteur
     *
     * @return self
     */
    public function setNumeroExpediteur($numeroExpediteur)
    {
        if (is_null($numeroExpediteur)) {
            throw new \InvalidArgumentException('non-nullable numeroExpediteur cannot be null');
        }

        if ((mb_strlen($numeroExpediteur) < 1)) {
            throw new \InvalidArgumentException('invalid length for $numeroExpediteur when calling AnnulationDto., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d{4,15}$/", ObjectSerializer::toString($numeroExpediteur)))) {
            throw new \InvalidArgumentException("invalid value for \$numeroExpediteur when calling AnnulationDto., must conform to the pattern /^\\d{4,15}$/.");
        }

        $this->container['numeroExpediteur'] = $numeroExpediteur;

        return $this;
    }

    /**
     * Gets indicatifExpediteur
     *
     * @return string
     */
    public function getIndicatifExpediteur()
    {
        return $this->container['indicatifExpediteur'];
    }

    /**
     * Sets indicatifExpediteur
     *
     * @param string $indicatifExpediteur indicatifExpediteur
     *
     * @return self
     */
    public function setIndicatifExpediteur($indicatifExpediteur)
    {
        if (is_null($indicatifExpediteur)) {
            throw new \InvalidArgumentException('non-nullable indicatifExpediteur cannot be null');
        }

        if ((mb_strlen($indicatifExpediteur) < 1)) {
            throw new \InvalidArgumentException('invalid length for $indicatifExpediteur when calling AnnulationDto., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\+?\\d{2,6}$/", ObjectSerializer::toString($indicatifExpediteur)))) {
            throw new \InvalidArgumentException("invalid value for \$indicatifExpediteur when calling AnnulationDto., must conform to the pattern /^\\+?\\d{2,6}$/.");
        }

        $this->container['indicatifExpediteur'] = $indicatifExpediteur;

        return $this;
    }

    /**
     * Gets adresseIP
     *
     * @return string|null
     */
    public function getAdresseIP()
    {
        return $this->container['adresseIP'];
    }

    /**
     * Sets adresseIP
     *
     * @param string|null $adresseIP adresseIP
     *
     * @return self
     */
    public function setAdresseIP($adresseIP)
    {
        if (is_null($adresseIP)) {
            throw new \InvalidArgumentException('non-nullable adresseIP cannot be null');
        }
        if ((mb_strlen($adresseIP) > 45)) {
            throw new \InvalidArgumentException('invalid length for $adresseIP when calling AnnulationDto., must be smaller than or equal to 45.');
        }
        if ((mb_strlen($adresseIP) < 0)) {
            throw new \InvalidArgumentException('invalid length for $adresseIP when calling AnnulationDto., must be bigger than or equal to 0.');
        }

        $this->container['adresseIP'] = $adresseIP;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


