<?php
/**
 * CalculeFraisOperationRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * CalculeFraisOperationRequest Class Doc Comment
 *
 * @category Class
 * @description Détails pour le calcul des frais d&#39;envoi
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CalculeFraisOperationRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CalculeFraisOperationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'indicatifExpediteur' => 'string',
        'numeroExpediteur' => 'string',
        'montant' => 'float',
        'fraisInclus' => 'bool',
        'villeExpedition' => 'string',
        'villeDestination' => 'string',
        'profil' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'indicatifExpediteur' => null,
        'numeroExpediteur' => null,
        'montant' => 'double',
        'fraisInclus' => null,
        'villeExpedition' => null,
        'villeDestination' => null,
        'profil' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'indicatifExpediteur' => false,
        'numeroExpediteur' => false,
        'montant' => false,
        'fraisInclus' => false,
        'villeExpedition' => false,
        'villeDestination' => false,
        'profil' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'indicatifExpediteur' => 'indicatifExpediteur',
        'numeroExpediteur' => 'numeroExpediteur',
        'montant' => 'montant',
        'fraisInclus' => 'fraisInclus',
        'villeExpedition' => 'villeExpedition',
        'villeDestination' => 'villeDestination',
        'profil' => 'profil'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'indicatifExpediteur' => 'setIndicatifExpediteur',
        'numeroExpediteur' => 'setNumeroExpediteur',
        'montant' => 'setMontant',
        'fraisInclus' => 'setFraisInclus',
        'villeExpedition' => 'setVilleExpedition',
        'villeDestination' => 'setVilleDestination',
        'profil' => 'setProfil'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'indicatifExpediteur' => 'getIndicatifExpediteur',
        'numeroExpediteur' => 'getNumeroExpediteur',
        'montant' => 'getMontant',
        'fraisInclus' => 'getFraisInclus',
        'villeExpedition' => 'getVilleExpedition',
        'villeDestination' => 'getVilleDestination',
        'profil' => 'getProfil'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PROFIL_CCP = 'CCP';
    public const PROFIL_BIN = 'BIN';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProfilAllowableValues()
    {
        return [
            self::PROFIL_CCP,
            self::PROFIL_BIN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('indicatifExpediteur', $data ?? [], null);
        $this->setIfExists('numeroExpediteur', $data ?? [], null);
        $this->setIfExists('montant', $data ?? [], null);
        $this->setIfExists('fraisInclus', $data ?? [], null);
        $this->setIfExists('villeExpedition', $data ?? [], null);
        $this->setIfExists('villeDestination', $data ?? [], null);
        $this->setIfExists('profil', $data ?? [], 'CCP');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['indicatifExpediteur'] === null) {
            $invalidProperties[] = "'indicatifExpediteur' can't be null";
        }
        if ((mb_strlen($this->container['indicatifExpediteur']) < 1)) {
            $invalidProperties[] = "invalid value for 'indicatifExpediteur', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\+?\\d{2,6}$/", $this->container['indicatifExpediteur'])) {
            $invalidProperties[] = "invalid value for 'indicatifExpediteur', must be conform to the pattern /^\\+?\\d{2,6}$/.";
        }

        if ($this->container['numeroExpediteur'] === null) {
            $invalidProperties[] = "'numeroExpediteur' can't be null";
        }
        if ((mb_strlen($this->container['numeroExpediteur']) < 1)) {
            $invalidProperties[] = "invalid value for 'numeroExpediteur', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\d{4,15}$/", $this->container['numeroExpediteur'])) {
            $invalidProperties[] = "invalid value for 'numeroExpediteur', must be conform to the pattern /^\\d{4,15}$/.";
        }

        if ($this->container['montant'] === null) {
            $invalidProperties[] = "'montant' can't be null";
        }
        if ($this->container['fraisInclus'] === null) {
            $invalidProperties[] = "'fraisInclus' can't be null";
        }
        if ($this->container['villeExpedition'] === null) {
            $invalidProperties[] = "'villeExpedition' can't be null";
        }
        if ((mb_strlen($this->container['villeExpedition']) < 1)) {
            $invalidProperties[] = "invalid value for 'villeExpedition', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['villeDestination'] === null) {
            $invalidProperties[] = "'villeDestination' can't be null";
        }
        if ((mb_strlen($this->container['villeDestination']) < 1)) {
            $invalidProperties[] = "invalid value for 'villeDestination', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getProfilAllowableValues();
        if (!is_null($this->container['profil']) && !in_array($this->container['profil'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'profil', must be one of '%s'",
                $this->container['profil'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets indicatifExpediteur
     *
     * @return string
     */
    public function getIndicatifExpediteur()
    {
        return $this->container['indicatifExpediteur'];
    }

    /**
     * Sets indicatifExpediteur
     *
     * @param string $indicatifExpediteur indicatifExpediteur
     *
     * @return self
     */
    public function setIndicatifExpediteur($indicatifExpediteur)
    {
        if (is_null($indicatifExpediteur)) {
            throw new \InvalidArgumentException('non-nullable indicatifExpediteur cannot be null');
        }

        if ((mb_strlen($indicatifExpediteur) < 1)) {
            throw new \InvalidArgumentException('invalid length for $indicatifExpediteur when calling CalculeFraisOperationRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\+?\\d{2,6}$/", ObjectSerializer::toString($indicatifExpediteur)))) {
            throw new \InvalidArgumentException("invalid value for \$indicatifExpediteur when calling CalculeFraisOperationRequest., must conform to the pattern /^\\+?\\d{2,6}$/.");
        }

        $this->container['indicatifExpediteur'] = $indicatifExpediteur;

        return $this;
    }

    /**
     * Gets numeroExpediteur
     *
     * @return string
     */
    public function getNumeroExpediteur()
    {
        return $this->container['numeroExpediteur'];
    }

    /**
     * Sets numeroExpediteur
     *
     * @param string $numeroExpediteur numeroExpediteur
     *
     * @return self
     */
    public function setNumeroExpediteur($numeroExpediteur)
    {
        if (is_null($numeroExpediteur)) {
            throw new \InvalidArgumentException('non-nullable numeroExpediteur cannot be null');
        }

        if ((mb_strlen($numeroExpediteur) < 1)) {
            throw new \InvalidArgumentException('invalid length for $numeroExpediteur when calling CalculeFraisOperationRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d{4,15}$/", ObjectSerializer::toString($numeroExpediteur)))) {
            throw new \InvalidArgumentException("invalid value for \$numeroExpediteur when calling CalculeFraisOperationRequest., must conform to the pattern /^\\d{4,15}$/.");
        }

        $this->container['numeroExpediteur'] = $numeroExpediteur;

        return $this;
    }

    /**
     * Gets montant
     *
     * @return float
     */
    public function getMontant()
    {
        return $this->container['montant'];
    }

    /**
     * Sets montant
     *
     * @param float $montant montant
     *
     * @return self
     */
    public function setMontant($montant)
    {
        if (is_null($montant)) {
            throw new \InvalidArgumentException('non-nullable montant cannot be null');
        }
        $this->container['montant'] = $montant;

        return $this;
    }

    /**
     * Gets fraisInclus
     *
     * @return bool
     */
    public function getFraisInclus()
    {
        return $this->container['fraisInclus'];
    }

    /**
     * Sets fraisInclus
     *
     * @param bool $fraisInclus fraisInclus
     *
     * @return self
     */
    public function setFraisInclus($fraisInclus)
    {
        if (is_null($fraisInclus)) {
            throw new \InvalidArgumentException('non-nullable fraisInclus cannot be null');
        }
        $this->container['fraisInclus'] = $fraisInclus;

        return $this;
    }

    /**
     * Gets villeExpedition
     *
     * @return string
     */
    public function getVilleExpedition()
    {
        return $this->container['villeExpedition'];
    }

    /**
     * Sets villeExpedition
     *
     * @param string $villeExpedition villeExpedition
     *
     * @return self
     */
    public function setVilleExpedition($villeExpedition)
    {
        if (is_null($villeExpedition)) {
            throw new \InvalidArgumentException('non-nullable villeExpedition cannot be null');
        }

        if ((mb_strlen($villeExpedition) < 1)) {
            throw new \InvalidArgumentException('invalid length for $villeExpedition when calling CalculeFraisOperationRequest., must be bigger than or equal to 1.');
        }

        $this->container['villeExpedition'] = $villeExpedition;

        return $this;
    }

    /**
     * Gets villeDestination
     *
     * @return string
     */
    public function getVilleDestination()
    {
        return $this->container['villeDestination'];
    }

    /**
     * Sets villeDestination
     *
     * @param string $villeDestination villeDestination
     *
     * @return self
     */
    public function setVilleDestination($villeDestination)
    {
        if (is_null($villeDestination)) {
            throw new \InvalidArgumentException('non-nullable villeDestination cannot be null');
        }

        if ((mb_strlen($villeDestination) < 1)) {
            throw new \InvalidArgumentException('invalid length for $villeDestination when calling CalculeFraisOperationRequest., must be bigger than or equal to 1.');
        }

        $this->container['villeDestination'] = $villeDestination;

        return $this;
    }

    /**
     * Gets profil
     *
     * @return string|null
     */
    public function getProfil()
    {
        return $this->container['profil'];
    }

    /**
     * Sets profil
     *
     * @param string|null $profil Grille tarifaire du reseau de retrait cash : CCP (Niger Poste, defaut) ou BIN.
     *
     * @return self
     */
    public function setProfil($profil)
    {
        if (is_null($profil)) {
            throw new \InvalidArgumentException('non-nullable profil cannot be null');
        }
        $allowedValues = $this->getProfilAllowableValues();
        if (!in_array($profil, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'profil', must be one of '%s'",
                    $profil,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['profil'] = $profil;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


