<?php
/**
 * EnvoiInterPartenaireRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * EnvoiInterPartenaireRequest Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EnvoiInterPartenaireRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EnvoiInterPartenaireRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'requestId' => 'string',
        'partenaireDestinataireAlias' => 'string',
        'compteDestinataire' => 'string',
        'montantTransaction' => 'float',
        'typeFraisEnvoi' => 'string',
        'motifTransaction' => 'string',
        'compteExpediteur' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'requestId' => null,
        'partenaireDestinataireAlias' => null,
        'compteDestinataire' => null,
        'montantTransaction' => 'double',
        'typeFraisEnvoi' => null,
        'motifTransaction' => null,
        'compteExpediteur' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'requestId' => false,
        'partenaireDestinataireAlias' => false,
        'compteDestinataire' => false,
        'montantTransaction' => false,
        'typeFraisEnvoi' => false,
        'motifTransaction' => false,
        'compteExpediteur' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'requestId' => 'requestId',
        'partenaireDestinataireAlias' => 'partenaireDestinataireAlias',
        'compteDestinataire' => 'compteDestinataire',
        'montantTransaction' => 'montantTransaction',
        'typeFraisEnvoi' => 'typeFraisEnvoi',
        'motifTransaction' => 'motifTransaction',
        'compteExpediteur' => 'compteExpediteur'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'requestId' => 'setRequestId',
        'partenaireDestinataireAlias' => 'setPartenaireDestinataireAlias',
        'compteDestinataire' => 'setCompteDestinataire',
        'montantTransaction' => 'setMontantTransaction',
        'typeFraisEnvoi' => 'setTypeFraisEnvoi',
        'motifTransaction' => 'setMotifTransaction',
        'compteExpediteur' => 'setCompteExpediteur'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'requestId' => 'getRequestId',
        'partenaireDestinataireAlias' => 'getPartenaireDestinataireAlias',
        'compteDestinataire' => 'getCompteDestinataire',
        'montantTransaction' => 'getMontantTransaction',
        'typeFraisEnvoi' => 'getTypeFraisEnvoi',
        'motifTransaction' => 'getMotifTransaction',
        'compteExpediteur' => 'getCompteExpediteur'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('partenaireDestinataireAlias', $data ?? [], null);
        $this->setIfExists('compteDestinataire', $data ?? [], null);
        $this->setIfExists('montantTransaction', $data ?? [], null);
        $this->setIfExists('typeFraisEnvoi', $data ?? [], null);
        $this->setIfExists('motifTransaction', $data ?? [], null);
        $this->setIfExists('compteExpediteur', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['requestId'] === null) {
            $invalidProperties[] = "'requestId' can't be null";
        }
        if ($this->container['partenaireDestinataireAlias'] === null) {
            $invalidProperties[] = "'partenaireDestinataireAlias' can't be null";
        }
        if ($this->container['montantTransaction'] === null) {
            $invalidProperties[] = "'montantTransaction' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets requestId
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string $requestId Votre référence d'opération (idempotence).
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }
        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets partenaireDestinataireAlias
     *
     * @return string
     */
    public function getPartenaireDestinataireAlias()
    {
        return $this->container['partenaireDestinataireAlias'];
    }

    /**
     * Sets partenaireDestinataireAlias
     *
     * @param string $partenaireDestinataireAlias Alias du partenaire destinataire (même organisation).
     *
     * @return self
     */
    public function setPartenaireDestinataireAlias($partenaireDestinataireAlias)
    {
        if (is_null($partenaireDestinataireAlias)) {
            throw new \InvalidArgumentException('non-nullable partenaireDestinataireAlias cannot be null');
        }
        $this->container['partenaireDestinataireAlias'] = $partenaireDestinataireAlias;

        return $this;
    }

    /**
     * Gets compteDestinataire
     *
     * @return string|null
     */
    public function getCompteDestinataire()
    {
        return $this->container['compteDestinataire'];
    }

    /**
     * Sets compteDestinataire
     *
     * @param string|null $compteDestinataire Libellé du compte destinataire (optionnel si unique).
     *
     * @return self
     */
    public function setCompteDestinataire($compteDestinataire)
    {
        if (is_null($compteDestinataire)) {
            throw new \InvalidArgumentException('non-nullable compteDestinataire cannot be null');
        }
        $this->container['compteDestinataire'] = $compteDestinataire;

        return $this;
    }

    /**
     * Gets montantTransaction
     *
     * @return float
     */
    public function getMontantTransaction()
    {
        return $this->container['montantTransaction'];
    }

    /**
     * Sets montantTransaction
     *
     * @param float $montantTransaction montantTransaction
     *
     * @return self
     */
    public function setMontantTransaction($montantTransaction)
    {
        if (is_null($montantTransaction)) {
            throw new \InvalidArgumentException('non-nullable montantTransaction cannot be null');
        }
        $this->container['montantTransaction'] = $montantTransaction;

        return $this;
    }

    /**
     * Gets typeFraisEnvoi
     *
     * @return string|null
     */
    public function getTypeFraisEnvoi()
    {
        return $this->container['typeFraisEnvoi'];
    }

    /**
     * Sets typeFraisEnvoi
     *
     * @param string|null $typeFraisEnvoi fraisApars (défaut) ou fraisInclus.
     *
     * @return self
     */
    public function setTypeFraisEnvoi($typeFraisEnvoi)
    {
        if (is_null($typeFraisEnvoi)) {
            throw new \InvalidArgumentException('non-nullable typeFraisEnvoi cannot be null');
        }
        $this->container['typeFraisEnvoi'] = $typeFraisEnvoi;

        return $this;
    }

    /**
     * Gets motifTransaction
     *
     * @return string|null
     */
    public function getMotifTransaction()
    {
        return $this->container['motifTransaction'];
    }

    /**
     * Sets motifTransaction
     *
     * @param string|null $motifTransaction motifTransaction
     *
     * @return self
     */
    public function setMotifTransaction($motifTransaction)
    {
        if (is_null($motifTransaction)) {
            throw new \InvalidArgumentException('non-nullable motifTransaction cannot be null');
        }
        $this->container['motifTransaction'] = $motifTransaction;

        return $this;
    }

    /**
     * Gets compteExpediteur
     *
     * @return string|null
     */
    public function getCompteExpediteur()
    {
        return $this->container['compteExpediteur'];
    }

    /**
     * Sets compteExpediteur
     *
     * @param string|null $compteExpediteur Libellé du compte expéditeur (optionnel si unique).
     *
     * @return self
     */
    public function setCompteExpediteur($compteExpediteur)
    {
        if (is_null($compteExpediteur)) {
            throw new \InvalidArgumentException('non-nullable compteExpediteur cannot be null');
        }
        $this->container['compteExpediteur'] = $compteExpediteur;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


