<?php
/**
 * ModelEditEnvoieRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * ModelEditEnvoieRequest Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelEditEnvoieRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ModelEditEnvoieRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'villeDestination' => 'string',
        'nomDestinateur' => 'string',
        'prenomDestinateur' => 'string',
        'nomExpediteur' => 'string',
        'prenomExpediteur' => 'string',
        'phoneExpediteur' => 'string',
        'phoneDestinateur' => 'string',
        'motifEnvoi' => 'string',
        'codeEnvoi' => 'string',
        'montantEnvoi' => 'float',
        'fraisEnvoi' => 'float',
        'total' => 'float',
        'fraisInclus' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'villeDestination' => null,
        'nomDestinateur' => null,
        'prenomDestinateur' => null,
        'nomExpediteur' => null,
        'prenomExpediteur' => null,
        'phoneExpediteur' => null,
        'phoneDestinateur' => null,
        'motifEnvoi' => null,
        'codeEnvoi' => null,
        'montantEnvoi' => 'double',
        'fraisEnvoi' => 'double',
        'total' => 'double',
        'fraisInclus' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'villeDestination' => false,
        'nomDestinateur' => false,
        'prenomDestinateur' => false,
        'nomExpediteur' => false,
        'prenomExpediteur' => false,
        'phoneExpediteur' => false,
        'phoneDestinateur' => false,
        'motifEnvoi' => false,
        'codeEnvoi' => false,
        'montantEnvoi' => false,
        'fraisEnvoi' => false,
        'total' => false,
        'fraisInclus' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'villeDestination' => 'villeDestination',
        'nomDestinateur' => 'nomDestinateur',
        'prenomDestinateur' => 'prenomDestinateur',
        'nomExpediteur' => 'nomExpediteur',
        'prenomExpediteur' => 'prenomExpediteur',
        'phoneExpediteur' => 'phoneExpediteur',
        'phoneDestinateur' => 'phoneDestinateur',
        'motifEnvoi' => 'motifEnvoi',
        'codeEnvoi' => 'codeEnvoi',
        'montantEnvoi' => 'montantEnvoi',
        'fraisEnvoi' => 'fraisEnvoi',
        'total' => 'total',
        'fraisInclus' => 'fraisInclus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'villeDestination' => 'setVilleDestination',
        'nomDestinateur' => 'setNomDestinateur',
        'prenomDestinateur' => 'setPrenomDestinateur',
        'nomExpediteur' => 'setNomExpediteur',
        'prenomExpediteur' => 'setPrenomExpediteur',
        'phoneExpediteur' => 'setPhoneExpediteur',
        'phoneDestinateur' => 'setPhoneDestinateur',
        'motifEnvoi' => 'setMotifEnvoi',
        'codeEnvoi' => 'setCodeEnvoi',
        'montantEnvoi' => 'setMontantEnvoi',
        'fraisEnvoi' => 'setFraisEnvoi',
        'total' => 'setTotal',
        'fraisInclus' => 'setFraisInclus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'villeDestination' => 'getVilleDestination',
        'nomDestinateur' => 'getNomDestinateur',
        'prenomDestinateur' => 'getPrenomDestinateur',
        'nomExpediteur' => 'getNomExpediteur',
        'prenomExpediteur' => 'getPrenomExpediteur',
        'phoneExpediteur' => 'getPhoneExpediteur',
        'phoneDestinateur' => 'getPhoneDestinateur',
        'motifEnvoi' => 'getMotifEnvoi',
        'codeEnvoi' => 'getCodeEnvoi',
        'montantEnvoi' => 'getMontantEnvoi',
        'fraisEnvoi' => 'getFraisEnvoi',
        'total' => 'getTotal',
        'fraisInclus' => 'getFraisInclus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('villeDestination', $data ?? [], null);
        $this->setIfExists('nomDestinateur', $data ?? [], null);
        $this->setIfExists('prenomDestinateur', $data ?? [], null);
        $this->setIfExists('nomExpediteur', $data ?? [], null);
        $this->setIfExists('prenomExpediteur', $data ?? [], null);
        $this->setIfExists('phoneExpediteur', $data ?? [], null);
        $this->setIfExists('phoneDestinateur', $data ?? [], null);
        $this->setIfExists('motifEnvoi', $data ?? [], null);
        $this->setIfExists('codeEnvoi', $data ?? [], null);
        $this->setIfExists('montantEnvoi', $data ?? [], null);
        $this->setIfExists('fraisEnvoi', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('fraisInclus', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets villeDestination
     *
     * @return string|null
     */
    public function getVilleDestination()
    {
        return $this->container['villeDestination'];
    }

    /**
     * Sets villeDestination
     *
     * @param string|null $villeDestination villeDestination
     *
     * @return self
     */
    public function setVilleDestination($villeDestination)
    {
        if (is_null($villeDestination)) {
            throw new \InvalidArgumentException('non-nullable villeDestination cannot be null');
        }
        $this->container['villeDestination'] = $villeDestination;

        return $this;
    }

    /**
     * Gets nomDestinateur
     *
     * @return string|null
     */
    public function getNomDestinateur()
    {
        return $this->container['nomDestinateur'];
    }

    /**
     * Sets nomDestinateur
     *
     * @param string|null $nomDestinateur nomDestinateur
     *
     * @return self
     */
    public function setNomDestinateur($nomDestinateur)
    {
        if (is_null($nomDestinateur)) {
            throw new \InvalidArgumentException('non-nullable nomDestinateur cannot be null');
        }
        $this->container['nomDestinateur'] = $nomDestinateur;

        return $this;
    }

    /**
     * Gets prenomDestinateur
     *
     * @return string|null
     */
    public function getPrenomDestinateur()
    {
        return $this->container['prenomDestinateur'];
    }

    /**
     * Sets prenomDestinateur
     *
     * @param string|null $prenomDestinateur prenomDestinateur
     *
     * @return self
     */
    public function setPrenomDestinateur($prenomDestinateur)
    {
        if (is_null($prenomDestinateur)) {
            throw new \InvalidArgumentException('non-nullable prenomDestinateur cannot be null');
        }
        $this->container['prenomDestinateur'] = $prenomDestinateur;

        return $this;
    }

    /**
     * Gets nomExpediteur
     *
     * @return string|null
     */
    public function getNomExpediteur()
    {
        return $this->container['nomExpediteur'];
    }

    /**
     * Sets nomExpediteur
     *
     * @param string|null $nomExpediteur nomExpediteur
     *
     * @return self
     */
    public function setNomExpediteur($nomExpediteur)
    {
        if (is_null($nomExpediteur)) {
            throw new \InvalidArgumentException('non-nullable nomExpediteur cannot be null');
        }
        $this->container['nomExpediteur'] = $nomExpediteur;

        return $this;
    }

    /**
     * Gets prenomExpediteur
     *
     * @return string|null
     */
    public function getPrenomExpediteur()
    {
        return $this->container['prenomExpediteur'];
    }

    /**
     * Sets prenomExpediteur
     *
     * @param string|null $prenomExpediteur prenomExpediteur
     *
     * @return self
     */
    public function setPrenomExpediteur($prenomExpediteur)
    {
        if (is_null($prenomExpediteur)) {
            throw new \InvalidArgumentException('non-nullable prenomExpediteur cannot be null');
        }
        $this->container['prenomExpediteur'] = $prenomExpediteur;

        return $this;
    }

    /**
     * Gets phoneExpediteur
     *
     * @return string|null
     */
    public function getPhoneExpediteur()
    {
        return $this->container['phoneExpediteur'];
    }

    /**
     * Sets phoneExpediteur
     *
     * @param string|null $phoneExpediteur phoneExpediteur
     *
     * @return self
     */
    public function setPhoneExpediteur($phoneExpediteur)
    {
        if (is_null($phoneExpediteur)) {
            throw new \InvalidArgumentException('non-nullable phoneExpediteur cannot be null');
        }
        $this->container['phoneExpediteur'] = $phoneExpediteur;

        return $this;
    }

    /**
     * Gets phoneDestinateur
     *
     * @return string|null
     */
    public function getPhoneDestinateur()
    {
        return $this->container['phoneDestinateur'];
    }

    /**
     * Sets phoneDestinateur
     *
     * @param string|null $phoneDestinateur phoneDestinateur
     *
     * @return self
     */
    public function setPhoneDestinateur($phoneDestinateur)
    {
        if (is_null($phoneDestinateur)) {
            throw new \InvalidArgumentException('non-nullable phoneDestinateur cannot be null');
        }
        $this->container['phoneDestinateur'] = $phoneDestinateur;

        return $this;
    }

    /**
     * Gets motifEnvoi
     *
     * @return string|null
     */
    public function getMotifEnvoi()
    {
        return $this->container['motifEnvoi'];
    }

    /**
     * Sets motifEnvoi
     *
     * @param string|null $motifEnvoi motifEnvoi
     *
     * @return self
     */
    public function setMotifEnvoi($motifEnvoi)
    {
        if (is_null($motifEnvoi)) {
            throw new \InvalidArgumentException('non-nullable motifEnvoi cannot be null');
        }
        $this->container['motifEnvoi'] = $motifEnvoi;

        return $this;
    }

    /**
     * Gets codeEnvoi
     *
     * @return string|null
     */
    public function getCodeEnvoi()
    {
        return $this->container['codeEnvoi'];
    }

    /**
     * Sets codeEnvoi
     *
     * @param string|null $codeEnvoi codeEnvoi
     *
     * @return self
     */
    public function setCodeEnvoi($codeEnvoi)
    {
        if (is_null($codeEnvoi)) {
            throw new \InvalidArgumentException('non-nullable codeEnvoi cannot be null');
        }
        $this->container['codeEnvoi'] = $codeEnvoi;

        return $this;
    }

    /**
     * Gets montantEnvoi
     *
     * @return float|null
     */
    public function getMontantEnvoi()
    {
        return $this->container['montantEnvoi'];
    }

    /**
     * Sets montantEnvoi
     *
     * @param float|null $montantEnvoi montantEnvoi
     *
     * @return self
     */
    public function setMontantEnvoi($montantEnvoi)
    {
        if (is_null($montantEnvoi)) {
            throw new \InvalidArgumentException('non-nullable montantEnvoi cannot be null');
        }
        $this->container['montantEnvoi'] = $montantEnvoi;

        return $this;
    }

    /**
     * Gets fraisEnvoi
     *
     * @return float|null
     */
    public function getFraisEnvoi()
    {
        return $this->container['fraisEnvoi'];
    }

    /**
     * Sets fraisEnvoi
     *
     * @param float|null $fraisEnvoi fraisEnvoi
     *
     * @return self
     */
    public function setFraisEnvoi($fraisEnvoi)
    {
        if (is_null($fraisEnvoi)) {
            throw new \InvalidArgumentException('non-nullable fraisEnvoi cannot be null');
        }
        $this->container['fraisEnvoi'] = $fraisEnvoi;

        return $this;
    }

    /**
     * Gets total
     *
     * @return float|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param float|null $total total
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets fraisInclus
     *
     * @return bool|null
     */
    public function getFraisInclus()
    {
        return $this->container['fraisInclus'];
    }

    /**
     * Sets fraisInclus
     *
     * @param bool|null $fraisInclus fraisInclus
     *
     * @return self
     */
    public function setFraisInclus($fraisInclus)
    {
        if (is_null($fraisInclus)) {
            throw new \InvalidArgumentException('non-nullable fraisInclus cannot be null');
        }
        $this->container['fraisInclus'] = $fraisInclus;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


