<?php
/**
 * PartenaireToCashDtoV2
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * PartenaireToCashDtoV2 Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PartenaireToCashDtoV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PartenaireToCashDtoV2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'nom' => 'string',
        'prenom' => 'string',
        'indicatif' => 'string',
        'numero' => 'string',
        'dateNaissance' => '\DateTime',
        'lieuNaissance' => 'string',
        'situationMatrimoniale' => 'string',
        'genre' => 'string',
        'profession' => 'string',
        'adresse' => 'string',
        'villeResidence' => 'string',
        'paysResidence' => 'string',
        'typePiece' => 'string',
        'numeroPiece' => 'string',
        'dateDelivrance' => '\DateTime',
        'lieuDelivrance' => 'string',
        'autorite' => 'string',
        'photoPieceIdentiteRecto' => 'string',
        'photoPieceIdentiteVerso' => 'string',
        'photoIdentite' => 'string',
        'requestId' => 'string',
        'fraisInclus' => 'bool',
        'montant' => 'float',
        'villeDestination' => 'string',
        'nomDestinataire' => 'string',
        'prenomDestinataire' => 'string',
        'indicatifDestinataire' => 'string',
        'numeroDestinataire' => 'string',
        'motifTransaction' => 'string',
        'adresseIp' => 'string',
        'urlCallback' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'nom' => null,
        'prenom' => null,
        'indicatif' => null,
        'numero' => null,
        'dateNaissance' => 'date-time',
        'lieuNaissance' => null,
        'situationMatrimoniale' => null,
        'genre' => null,
        'profession' => null,
        'adresse' => null,
        'villeResidence' => null,
        'paysResidence' => null,
        'typePiece' => null,
        'numeroPiece' => null,
        'dateDelivrance' => 'date-time',
        'lieuDelivrance' => null,
        'autorite' => null,
        'photoPieceIdentiteRecto' => null,
        'photoPieceIdentiteVerso' => null,
        'photoIdentite' => null,
        'requestId' => null,
        'fraisInclus' => null,
        'montant' => 'double',
        'villeDestination' => null,
        'nomDestinataire' => null,
        'prenomDestinataire' => null,
        'indicatifDestinataire' => null,
        'numeroDestinataire' => null,
        'motifTransaction' => null,
        'adresseIp' => null,
        'urlCallback' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'nom' => false,
        'prenom' => false,
        'indicatif' => false,
        'numero' => false,
        'dateNaissance' => false,
        'lieuNaissance' => false,
        'situationMatrimoniale' => false,
        'genre' => false,
        'profession' => false,
        'adresse' => false,
        'villeResidence' => false,
        'paysResidence' => false,
        'typePiece' => false,
        'numeroPiece' => false,
        'dateDelivrance' => false,
        'lieuDelivrance' => false,
        'autorite' => false,
        'photoPieceIdentiteRecto' => false,
        'photoPieceIdentiteVerso' => false,
        'photoIdentite' => false,
        'requestId' => false,
        'fraisInclus' => false,
        'montant' => false,
        'villeDestination' => false,
        'nomDestinataire' => false,
        'prenomDestinataire' => false,
        'indicatifDestinataire' => false,
        'numeroDestinataire' => false,
        'motifTransaction' => false,
        'adresseIp' => false,
        'urlCallback' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nom' => 'nom',
        'prenom' => 'prenom',
        'indicatif' => 'indicatif',
        'numero' => 'numero',
        'dateNaissance' => 'dateNaissance',
        'lieuNaissance' => 'lieuNaissance',
        'situationMatrimoniale' => 'situationMatrimoniale',
        'genre' => 'genre',
        'profession' => 'profession',
        'adresse' => 'adresse',
        'villeResidence' => 'villeResidence',
        'paysResidence' => 'paysResidence',
        'typePiece' => 'typePiece',
        'numeroPiece' => 'numeroPiece',
        'dateDelivrance' => 'dateDelivrance',
        'lieuDelivrance' => 'lieuDelivrance',
        'autorite' => 'autorite',
        'photoPieceIdentiteRecto' => 'photoPieceIdentiteRecto',
        'photoPieceIdentiteVerso' => 'photoPieceIdentiteVerso',
        'photoIdentite' => 'photoIdentite',
        'requestId' => 'requestId',
        'fraisInclus' => 'fraisInclus',
        'montant' => 'montant',
        'villeDestination' => 'villeDestination',
        'nomDestinataire' => 'nomDestinataire',
        'prenomDestinataire' => 'prenomDestinataire',
        'indicatifDestinataire' => 'indicatifDestinataire',
        'numeroDestinataire' => 'numeroDestinataire',
        'motifTransaction' => 'motifTransaction',
        'adresseIp' => 'adresseIp',
        'urlCallback' => 'urlCallback'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nom' => 'setNom',
        'prenom' => 'setPrenom',
        'indicatif' => 'setIndicatif',
        'numero' => 'setNumero',
        'dateNaissance' => 'setDateNaissance',
        'lieuNaissance' => 'setLieuNaissance',
        'situationMatrimoniale' => 'setSituationMatrimoniale',
        'genre' => 'setGenre',
        'profession' => 'setProfession',
        'adresse' => 'setAdresse',
        'villeResidence' => 'setVilleResidence',
        'paysResidence' => 'setPaysResidence',
        'typePiece' => 'setTypePiece',
        'numeroPiece' => 'setNumeroPiece',
        'dateDelivrance' => 'setDateDelivrance',
        'lieuDelivrance' => 'setLieuDelivrance',
        'autorite' => 'setAutorite',
        'photoPieceIdentiteRecto' => 'setPhotoPieceIdentiteRecto',
        'photoPieceIdentiteVerso' => 'setPhotoPieceIdentiteVerso',
        'photoIdentite' => 'setPhotoIdentite',
        'requestId' => 'setRequestId',
        'fraisInclus' => 'setFraisInclus',
        'montant' => 'setMontant',
        'villeDestination' => 'setVilleDestination',
        'nomDestinataire' => 'setNomDestinataire',
        'prenomDestinataire' => 'setPrenomDestinataire',
        'indicatifDestinataire' => 'setIndicatifDestinataire',
        'numeroDestinataire' => 'setNumeroDestinataire',
        'motifTransaction' => 'setMotifTransaction',
        'adresseIp' => 'setAdresseIp',
        'urlCallback' => 'setUrlCallback'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nom' => 'getNom',
        'prenom' => 'getPrenom',
        'indicatif' => 'getIndicatif',
        'numero' => 'getNumero',
        'dateNaissance' => 'getDateNaissance',
        'lieuNaissance' => 'getLieuNaissance',
        'situationMatrimoniale' => 'getSituationMatrimoniale',
        'genre' => 'getGenre',
        'profession' => 'getProfession',
        'adresse' => 'getAdresse',
        'villeResidence' => 'getVilleResidence',
        'paysResidence' => 'getPaysResidence',
        'typePiece' => 'getTypePiece',
        'numeroPiece' => 'getNumeroPiece',
        'dateDelivrance' => 'getDateDelivrance',
        'lieuDelivrance' => 'getLieuDelivrance',
        'autorite' => 'getAutorite',
        'photoPieceIdentiteRecto' => 'getPhotoPieceIdentiteRecto',
        'photoPieceIdentiteVerso' => 'getPhotoPieceIdentiteVerso',
        'photoIdentite' => 'getPhotoIdentite',
        'requestId' => 'getRequestId',
        'fraisInclus' => 'getFraisInclus',
        'montant' => 'getMontant',
        'villeDestination' => 'getVilleDestination',
        'nomDestinataire' => 'getNomDestinataire',
        'prenomDestinataire' => 'getPrenomDestinataire',
        'indicatifDestinataire' => 'getIndicatifDestinataire',
        'numeroDestinataire' => 'getNumeroDestinataire',
        'motifTransaction' => 'getMotifTransaction',
        'adresseIp' => 'getAdresseIp',
        'urlCallback' => 'getUrlCallback'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('nom', $data ?? [], null);
        $this->setIfExists('prenom', $data ?? [], null);
        $this->setIfExists('indicatif', $data ?? [], null);
        $this->setIfExists('numero', $data ?? [], null);
        $this->setIfExists('dateNaissance', $data ?? [], null);
        $this->setIfExists('lieuNaissance', $data ?? [], null);
        $this->setIfExists('situationMatrimoniale', $data ?? [], null);
        $this->setIfExists('genre', $data ?? [], null);
        $this->setIfExists('profession', $data ?? [], null);
        $this->setIfExists('adresse', $data ?? [], null);
        $this->setIfExists('villeResidence', $data ?? [], null);
        $this->setIfExists('paysResidence', $data ?? [], null);
        $this->setIfExists('typePiece', $data ?? [], null);
        $this->setIfExists('numeroPiece', $data ?? [], null);
        $this->setIfExists('dateDelivrance', $data ?? [], null);
        $this->setIfExists('lieuDelivrance', $data ?? [], null);
        $this->setIfExists('autorite', $data ?? [], null);
        $this->setIfExists('photoPieceIdentiteRecto', $data ?? [], null);
        $this->setIfExists('photoPieceIdentiteVerso', $data ?? [], null);
        $this->setIfExists('photoIdentite', $data ?? [], null);
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('fraisInclus', $data ?? [], null);
        $this->setIfExists('montant', $data ?? [], null);
        $this->setIfExists('villeDestination', $data ?? [], null);
        $this->setIfExists('nomDestinataire', $data ?? [], null);
        $this->setIfExists('prenomDestinataire', $data ?? [], null);
        $this->setIfExists('indicatifDestinataire', $data ?? [], null);
        $this->setIfExists('numeroDestinataire', $data ?? [], null);
        $this->setIfExists('motifTransaction', $data ?? [], null);
        $this->setIfExists('adresseIp', $data ?? [], null);
        $this->setIfExists('urlCallback', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['nom'] === null) {
            $invalidProperties[] = "'nom' can't be null";
        }
        if ((mb_strlen($this->container['nom']) > 100)) {
            $invalidProperties[] = "invalid value for 'nom', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['nom']) < 0)) {
            $invalidProperties[] = "invalid value for 'nom', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", $this->container['nom'])) {
            $invalidProperties[] = "invalid value for 'nom', must be conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.";
        }

        if ($this->container['prenom'] === null) {
            $invalidProperties[] = "'prenom' can't be null";
        }
        if ((mb_strlen($this->container['prenom']) > 100)) {
            $invalidProperties[] = "invalid value for 'prenom', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['prenom']) < 0)) {
            $invalidProperties[] = "invalid value for 'prenom', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", $this->container['prenom'])) {
            $invalidProperties[] = "invalid value for 'prenom', must be conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.";
        }

        if ($this->container['indicatif'] === null) {
            $invalidProperties[] = "'indicatif' can't be null";
        }
        if ((mb_strlen($this->container['indicatif']) < 1)) {
            $invalidProperties[] = "invalid value for 'indicatif', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\d{2,6}$/", $this->container['indicatif'])) {
            $invalidProperties[] = "invalid value for 'indicatif', must be conform to the pattern /^\\d{2,6}$/.";
        }

        if ($this->container['numero'] === null) {
            $invalidProperties[] = "'numero' can't be null";
        }
        if ((mb_strlen($this->container['numero']) < 1)) {
            $invalidProperties[] = "invalid value for 'numero', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\d{4,15}$/", $this->container['numero'])) {
            $invalidProperties[] = "invalid value for 'numero', must be conform to the pattern /^\\d{4,15}$/.";
        }

        if (!is_null($this->container['lieuNaissance']) && (mb_strlen($this->container['lieuNaissance']) > 100)) {
            $invalidProperties[] = "invalid value for 'lieuNaissance', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['lieuNaissance']) && (mb_strlen($this->container['lieuNaissance']) < 0)) {
            $invalidProperties[] = "invalid value for 'lieuNaissance', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['lieuNaissance']) && !preg_match("/^[\\p{L}\\s'.\\-,]*$/", $this->container['lieuNaissance'])) {
            $invalidProperties[] = "invalid value for 'lieuNaissance', must be conform to the pattern /^[\\p{L}\\s'.\\-,]*$/.";
        }

        if (!is_null($this->container['situationMatrimoniale']) && (mb_strlen($this->container['situationMatrimoniale']) > 50)) {
            $invalidProperties[] = "invalid value for 'situationMatrimoniale', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['situationMatrimoniale']) && (mb_strlen($this->container['situationMatrimoniale']) < 0)) {
            $invalidProperties[] = "invalid value for 'situationMatrimoniale', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['genre']) && (mb_strlen($this->container['genre']) > 20)) {
            $invalidProperties[] = "invalid value for 'genre', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['genre']) && (mb_strlen($this->container['genre']) < 0)) {
            $invalidProperties[] = "invalid value for 'genre', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['genre']) && !preg_match("/^[A-Za-z]*$/", $this->container['genre'])) {
            $invalidProperties[] = "invalid value for 'genre', must be conform to the pattern /^[A-Za-z]*$/.";
        }

        if (!is_null($this->container['profession']) && (mb_strlen($this->container['profession']) > 100)) {
            $invalidProperties[] = "invalid value for 'profession', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['profession']) && (mb_strlen($this->container['profession']) < 0)) {
            $invalidProperties[] = "invalid value for 'profession', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['profession']) && !preg_match("/^[\\p{L}\\s'.\\-,]*$/", $this->container['profession'])) {
            $invalidProperties[] = "invalid value for 'profession', must be conform to the pattern /^[\\p{L}\\s'.\\-,]*$/.";
        }

        if (!is_null($this->container['adresse']) && (mb_strlen($this->container['adresse']) > 200)) {
            $invalidProperties[] = "invalid value for 'adresse', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['adresse']) && (mb_strlen($this->container['adresse']) < 0)) {
            $invalidProperties[] = "invalid value for 'adresse', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['villeResidence']) && (mb_strlen($this->container['villeResidence']) > 100)) {
            $invalidProperties[] = "invalid value for 'villeResidence', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['villeResidence']) && (mb_strlen($this->container['villeResidence']) < 0)) {
            $invalidProperties[] = "invalid value for 'villeResidence', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['villeResidence']) && !preg_match("/^[\\p{L}\\s'.\\-]*$/", $this->container['villeResidence'])) {
            $invalidProperties[] = "invalid value for 'villeResidence', must be conform to the pattern /^[\\p{L}\\s'.\\-]*$/.";
        }

        if (!is_null($this->container['paysResidence']) && (mb_strlen($this->container['paysResidence']) > 100)) {
            $invalidProperties[] = "invalid value for 'paysResidence', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['paysResidence']) && (mb_strlen($this->container['paysResidence']) < 0)) {
            $invalidProperties[] = "invalid value for 'paysResidence', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['paysResidence']) && !preg_match("/^[\\p{L}\\s'.\\-]*$/", $this->container['paysResidence'])) {
            $invalidProperties[] = "invalid value for 'paysResidence', must be conform to the pattern /^[\\p{L}\\s'.\\-]*$/.";
        }

        if (!is_null($this->container['typePiece']) && (mb_strlen($this->container['typePiece']) > 50)) {
            $invalidProperties[] = "invalid value for 'typePiece', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['typePiece']) && (mb_strlen($this->container['typePiece']) < 0)) {
            $invalidProperties[] = "invalid value for 'typePiece', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['numeroPiece']) && (mb_strlen($this->container['numeroPiece']) > 50)) {
            $invalidProperties[] = "invalid value for 'numeroPiece', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['numeroPiece']) && (mb_strlen($this->container['numeroPiece']) < 0)) {
            $invalidProperties[] = "invalid value for 'numeroPiece', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['numeroPiece']) && !preg_match("/^[a-zA-Z0-9\\s\\-\/]*$/", $this->container['numeroPiece'])) {
            $invalidProperties[] = "invalid value for 'numeroPiece', must be conform to the pattern /^[a-zA-Z0-9\\s\\-\/]*$/.";
        }

        if (!is_null($this->container['lieuDelivrance']) && (mb_strlen($this->container['lieuDelivrance']) > 100)) {
            $invalidProperties[] = "invalid value for 'lieuDelivrance', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['lieuDelivrance']) && (mb_strlen($this->container['lieuDelivrance']) < 0)) {
            $invalidProperties[] = "invalid value for 'lieuDelivrance', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['lieuDelivrance']) && !preg_match("/^[\\p{L}\\s'.\\-,]*$/", $this->container['lieuDelivrance'])) {
            $invalidProperties[] = "invalid value for 'lieuDelivrance', must be conform to the pattern /^[\\p{L}\\s'.\\-,]*$/.";
        }

        if (!is_null($this->container['autorite']) && (mb_strlen($this->container['autorite']) > 100)) {
            $invalidProperties[] = "invalid value for 'autorite', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['autorite']) && (mb_strlen($this->container['autorite']) < 0)) {
            $invalidProperties[] = "invalid value for 'autorite', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['autorite']) && !preg_match("/^[\\p{L}\\s'.\\-]*$/", $this->container['autorite'])) {
            $invalidProperties[] = "invalid value for 'autorite', must be conform to the pattern /^[\\p{L}\\s'.\\-]*$/.";
        }

        if ($this->container['requestId'] === null) {
            $invalidProperties[] = "'requestId' can't be null";
        }
        if ((mb_strlen($this->container['requestId']) > 100)) {
            $invalidProperties[] = "invalid value for 'requestId', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['requestId']) < 4)) {
            $invalidProperties[] = "invalid value for 'requestId', the character length must be bigger than or equal to 4.";
        }

        if (!preg_match("/^[a-zA-Z0-9_\\-]{4,100}$/", $this->container['requestId'])) {
            $invalidProperties[] = "invalid value for 'requestId', must be conform to the pattern /^[a-zA-Z0-9_\\-]{4,100}$/.";
        }

        if ($this->container['fraisInclus'] === null) {
            $invalidProperties[] = "'fraisInclus' can't be null";
        }
        if ($this->container['montant'] === null) {
            $invalidProperties[] = "'montant' can't be null";
        }
        if (($this->container['montant'] > 100000000)) {
            $invalidProperties[] = "invalid value for 'montant', must be smaller than or equal to 100000000.";
        }

        if ($this->container['villeDestination'] === null) {
            $invalidProperties[] = "'villeDestination' can't be null";
        }
        if ((mb_strlen($this->container['villeDestination']) > 100)) {
            $invalidProperties[] = "invalid value for 'villeDestination', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['villeDestination']) < 0)) {
            $invalidProperties[] = "invalid value for 'villeDestination', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", $this->container['villeDestination'])) {
            $invalidProperties[] = "invalid value for 'villeDestination', must be conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.";
        }

        if ($this->container['nomDestinataire'] === null) {
            $invalidProperties[] = "'nomDestinataire' can't be null";
        }
        if ((mb_strlen($this->container['nomDestinataire']) > 100)) {
            $invalidProperties[] = "invalid value for 'nomDestinataire', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['nomDestinataire']) < 0)) {
            $invalidProperties[] = "invalid value for 'nomDestinataire', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", $this->container['nomDestinataire'])) {
            $invalidProperties[] = "invalid value for 'nomDestinataire', must be conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.";
        }

        if ($this->container['prenomDestinataire'] === null) {
            $invalidProperties[] = "'prenomDestinataire' can't be null";
        }
        if ((mb_strlen($this->container['prenomDestinataire']) > 100)) {
            $invalidProperties[] = "invalid value for 'prenomDestinataire', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['prenomDestinataire']) < 0)) {
            $invalidProperties[] = "invalid value for 'prenomDestinataire', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", $this->container['prenomDestinataire'])) {
            $invalidProperties[] = "invalid value for 'prenomDestinataire', must be conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.";
        }

        if ($this->container['indicatifDestinataire'] === null) {
            $invalidProperties[] = "'indicatifDestinataire' can't be null";
        }
        if ((mb_strlen($this->container['indicatifDestinataire']) < 1)) {
            $invalidProperties[] = "invalid value for 'indicatifDestinataire', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\d{2,6}$/", $this->container['indicatifDestinataire'])) {
            $invalidProperties[] = "invalid value for 'indicatifDestinataire', must be conform to the pattern /^\\d{2,6}$/.";
        }

        if ($this->container['numeroDestinataire'] === null) {
            $invalidProperties[] = "'numeroDestinataire' can't be null";
        }
        if ((mb_strlen($this->container['numeroDestinataire']) < 1)) {
            $invalidProperties[] = "invalid value for 'numeroDestinataire', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\\d{4,15}$/", $this->container['numeroDestinataire'])) {
            $invalidProperties[] = "invalid value for 'numeroDestinataire', must be conform to the pattern /^\\d{4,15}$/.";
        }

        if (!is_null($this->container['motifTransaction']) && (mb_strlen($this->container['motifTransaction']) > 500)) {
            $invalidProperties[] = "invalid value for 'motifTransaction', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['motifTransaction']) && (mb_strlen($this->container['motifTransaction']) < 0)) {
            $invalidProperties[] = "invalid value for 'motifTransaction', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['adresseIp']) && !preg_match("/^((\\d{1,3}\\.){3}\\d{1,3}|[0-9a-fA-F:]{3,39})?$/", $this->container['adresseIp'])) {
            $invalidProperties[] = "invalid value for 'adresseIp', must be conform to the pattern /^((\\d{1,3}\\.){3}\\d{1,3}|[0-9a-fA-F:]{3,39})?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom nom
     *
     * @return self
     */
    public function setNom($nom)
    {
        if (is_null($nom)) {
            throw new \InvalidArgumentException('non-nullable nom cannot be null');
        }
        if ((mb_strlen($nom) > 100)) {
            throw new \InvalidArgumentException('invalid length for $nom when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($nom) < 0)) {
            throw new \InvalidArgumentException('invalid length for $nom when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", ObjectSerializer::toString($nom)))) {
            throw new \InvalidArgumentException("invalid value for \$nom when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.");
        }

        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->container['prenom'];
    }

    /**
     * Sets prenom
     *
     * @param string $prenom prenom
     *
     * @return self
     */
    public function setPrenom($prenom)
    {
        if (is_null($prenom)) {
            throw new \InvalidArgumentException('non-nullable prenom cannot be null');
        }
        if ((mb_strlen($prenom) > 100)) {
            throw new \InvalidArgumentException('invalid length for $prenom when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($prenom) < 0)) {
            throw new \InvalidArgumentException('invalid length for $prenom when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", ObjectSerializer::toString($prenom)))) {
            throw new \InvalidArgumentException("invalid value for \$prenom when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.");
        }

        $this->container['prenom'] = $prenom;

        return $this;
    }

    /**
     * Gets indicatif
     *
     * @return string
     */
    public function getIndicatif()
    {
        return $this->container['indicatif'];
    }

    /**
     * Sets indicatif
     *
     * @param string $indicatif indicatif
     *
     * @return self
     */
    public function setIndicatif($indicatif)
    {
        if (is_null($indicatif)) {
            throw new \InvalidArgumentException('non-nullable indicatif cannot be null');
        }

        if ((mb_strlen($indicatif) < 1)) {
            throw new \InvalidArgumentException('invalid length for $indicatif when calling PartenaireToCashDtoV2., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d{2,6}$/", ObjectSerializer::toString($indicatif)))) {
            throw new \InvalidArgumentException("invalid value for \$indicatif when calling PartenaireToCashDtoV2., must conform to the pattern /^\\d{2,6}$/.");
        }

        $this->container['indicatif'] = $indicatif;

        return $this;
    }

    /**
     * Gets numero
     *
     * @return string
     */
    public function getNumero()
    {
        return $this->container['numero'];
    }

    /**
     * Sets numero
     *
     * @param string $numero numero
     *
     * @return self
     */
    public function setNumero($numero)
    {
        if (is_null($numero)) {
            throw new \InvalidArgumentException('non-nullable numero cannot be null');
        }

        if ((mb_strlen($numero) < 1)) {
            throw new \InvalidArgumentException('invalid length for $numero when calling PartenaireToCashDtoV2., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d{4,15}$/", ObjectSerializer::toString($numero)))) {
            throw new \InvalidArgumentException("invalid value for \$numero when calling PartenaireToCashDtoV2., must conform to the pattern /^\\d{4,15}$/.");
        }

        $this->container['numero'] = $numero;

        return $this;
    }

    /**
     * Gets dateNaissance
     *
     * @return \DateTime|null
     */
    public function getDateNaissance()
    {
        return $this->container['dateNaissance'];
    }

    /**
     * Sets dateNaissance
     *
     * @param \DateTime|null $dateNaissance dateNaissance
     *
     * @return self
     */
    public function setDateNaissance($dateNaissance)
    {
        if (is_null($dateNaissance)) {
            throw new \InvalidArgumentException('non-nullable dateNaissance cannot be null');
        }
        $this->container['dateNaissance'] = $dateNaissance;

        return $this;
    }

    /**
     * Gets lieuNaissance
     *
     * @return string|null
     */
    public function getLieuNaissance()
    {
        return $this->container['lieuNaissance'];
    }

    /**
     * Sets lieuNaissance
     *
     * @param string|null $lieuNaissance lieuNaissance
     *
     * @return self
     */
    public function setLieuNaissance($lieuNaissance)
    {
        if (is_null($lieuNaissance)) {
            throw new \InvalidArgumentException('non-nullable lieuNaissance cannot be null');
        }
        if ((mb_strlen($lieuNaissance) > 100)) {
            throw new \InvalidArgumentException('invalid length for $lieuNaissance when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($lieuNaissance) < 0)) {
            throw new \InvalidArgumentException('invalid length for $lieuNaissance when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-,]*$/", ObjectSerializer::toString($lieuNaissance)))) {
            throw new \InvalidArgumentException("invalid value for \$lieuNaissance when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-,]*$/.");
        }

        $this->container['lieuNaissance'] = $lieuNaissance;

        return $this;
    }

    /**
     * Gets situationMatrimoniale
     *
     * @return string|null
     */
    public function getSituationMatrimoniale()
    {
        return $this->container['situationMatrimoniale'];
    }

    /**
     * Sets situationMatrimoniale
     *
     * @param string|null $situationMatrimoniale situationMatrimoniale
     *
     * @return self
     */
    public function setSituationMatrimoniale($situationMatrimoniale)
    {
        if (is_null($situationMatrimoniale)) {
            throw new \InvalidArgumentException('non-nullable situationMatrimoniale cannot be null');
        }
        if ((mb_strlen($situationMatrimoniale) > 50)) {
            throw new \InvalidArgumentException('invalid length for $situationMatrimoniale when calling PartenaireToCashDtoV2., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($situationMatrimoniale) < 0)) {
            throw new \InvalidArgumentException('invalid length for $situationMatrimoniale when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }

        $this->container['situationMatrimoniale'] = $situationMatrimoniale;

        return $this;
    }

    /**
     * Gets genre
     *
     * @return string|null
     */
    public function getGenre()
    {
        return $this->container['genre'];
    }

    /**
     * Sets genre
     *
     * @param string|null $genre genre
     *
     * @return self
     */
    public function setGenre($genre)
    {
        if (is_null($genre)) {
            throw new \InvalidArgumentException('non-nullable genre cannot be null');
        }
        if ((mb_strlen($genre) > 20)) {
            throw new \InvalidArgumentException('invalid length for $genre when calling PartenaireToCashDtoV2., must be smaller than or equal to 20.');
        }
        if ((mb_strlen($genre) < 0)) {
            throw new \InvalidArgumentException('invalid length for $genre when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[A-Za-z]*$/", ObjectSerializer::toString($genre)))) {
            throw new \InvalidArgumentException("invalid value for \$genre when calling PartenaireToCashDtoV2., must conform to the pattern /^[A-Za-z]*$/.");
        }

        $this->container['genre'] = $genre;

        return $this;
    }

    /**
     * Gets profession
     *
     * @return string|null
     */
    public function getProfession()
    {
        return $this->container['profession'];
    }

    /**
     * Sets profession
     *
     * @param string|null $profession profession
     *
     * @return self
     */
    public function setProfession($profession)
    {
        if (is_null($profession)) {
            throw new \InvalidArgumentException('non-nullable profession cannot be null');
        }
        if ((mb_strlen($profession) > 100)) {
            throw new \InvalidArgumentException('invalid length for $profession when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($profession) < 0)) {
            throw new \InvalidArgumentException('invalid length for $profession when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-,]*$/", ObjectSerializer::toString($profession)))) {
            throw new \InvalidArgumentException("invalid value for \$profession when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-,]*$/.");
        }

        $this->container['profession'] = $profession;

        return $this;
    }

    /**
     * Gets adresse
     *
     * @return string|null
     */
    public function getAdresse()
    {
        return $this->container['adresse'];
    }

    /**
     * Sets adresse
     *
     * @param string|null $adresse adresse
     *
     * @return self
     */
    public function setAdresse($adresse)
    {
        if (is_null($adresse)) {
            throw new \InvalidArgumentException('non-nullable adresse cannot be null');
        }
        if ((mb_strlen($adresse) > 200)) {
            throw new \InvalidArgumentException('invalid length for $adresse when calling PartenaireToCashDtoV2., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($adresse) < 0)) {
            throw new \InvalidArgumentException('invalid length for $adresse when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }

        $this->container['adresse'] = $adresse;

        return $this;
    }

    /**
     * Gets villeResidence
     *
     * @return string|null
     */
    public function getVilleResidence()
    {
        return $this->container['villeResidence'];
    }

    /**
     * Sets villeResidence
     *
     * @param string|null $villeResidence villeResidence
     *
     * @return self
     */
    public function setVilleResidence($villeResidence)
    {
        if (is_null($villeResidence)) {
            throw new \InvalidArgumentException('non-nullable villeResidence cannot be null');
        }
        if ((mb_strlen($villeResidence) > 100)) {
            throw new \InvalidArgumentException('invalid length for $villeResidence when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($villeResidence) < 0)) {
            throw new \InvalidArgumentException('invalid length for $villeResidence when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]*$/", ObjectSerializer::toString($villeResidence)))) {
            throw new \InvalidArgumentException("invalid value for \$villeResidence when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]*$/.");
        }

        $this->container['villeResidence'] = $villeResidence;

        return $this;
    }

    /**
     * Gets paysResidence
     *
     * @return string|null
     */
    public function getPaysResidence()
    {
        return $this->container['paysResidence'];
    }

    /**
     * Sets paysResidence
     *
     * @param string|null $paysResidence paysResidence
     *
     * @return self
     */
    public function setPaysResidence($paysResidence)
    {
        if (is_null($paysResidence)) {
            throw new \InvalidArgumentException('non-nullable paysResidence cannot be null');
        }
        if ((mb_strlen($paysResidence) > 100)) {
            throw new \InvalidArgumentException('invalid length for $paysResidence when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($paysResidence) < 0)) {
            throw new \InvalidArgumentException('invalid length for $paysResidence when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]*$/", ObjectSerializer::toString($paysResidence)))) {
            throw new \InvalidArgumentException("invalid value for \$paysResidence when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]*$/.");
        }

        $this->container['paysResidence'] = $paysResidence;

        return $this;
    }

    /**
     * Gets typePiece
     *
     * @return string|null
     */
    public function getTypePiece()
    {
        return $this->container['typePiece'];
    }

    /**
     * Sets typePiece
     *
     * @param string|null $typePiece typePiece
     *
     * @return self
     */
    public function setTypePiece($typePiece)
    {
        if (is_null($typePiece)) {
            throw new \InvalidArgumentException('non-nullable typePiece cannot be null');
        }
        if ((mb_strlen($typePiece) > 50)) {
            throw new \InvalidArgumentException('invalid length for $typePiece when calling PartenaireToCashDtoV2., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($typePiece) < 0)) {
            throw new \InvalidArgumentException('invalid length for $typePiece when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }

        $this->container['typePiece'] = $typePiece;

        return $this;
    }

    /**
     * Gets numeroPiece
     *
     * @return string|null
     */
    public function getNumeroPiece()
    {
        return $this->container['numeroPiece'];
    }

    /**
     * Sets numeroPiece
     *
     * @param string|null $numeroPiece numeroPiece
     *
     * @return self
     */
    public function setNumeroPiece($numeroPiece)
    {
        if (is_null($numeroPiece)) {
            throw new \InvalidArgumentException('non-nullable numeroPiece cannot be null');
        }
        if ((mb_strlen($numeroPiece) > 50)) {
            throw new \InvalidArgumentException('invalid length for $numeroPiece when calling PartenaireToCashDtoV2., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($numeroPiece) < 0)) {
            throw new \InvalidArgumentException('invalid length for $numeroPiece when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[a-zA-Z0-9\\s\\-\/]*$/", ObjectSerializer::toString($numeroPiece)))) {
            throw new \InvalidArgumentException("invalid value for \$numeroPiece when calling PartenaireToCashDtoV2., must conform to the pattern /^[a-zA-Z0-9\\s\\-\/]*$/.");
        }

        $this->container['numeroPiece'] = $numeroPiece;

        return $this;
    }

    /**
     * Gets dateDelivrance
     *
     * @return \DateTime|null
     */
    public function getDateDelivrance()
    {
        return $this->container['dateDelivrance'];
    }

    /**
     * Sets dateDelivrance
     *
     * @param \DateTime|null $dateDelivrance dateDelivrance
     *
     * @return self
     */
    public function setDateDelivrance($dateDelivrance)
    {
        if (is_null($dateDelivrance)) {
            throw new \InvalidArgumentException('non-nullable dateDelivrance cannot be null');
        }
        $this->container['dateDelivrance'] = $dateDelivrance;

        return $this;
    }

    /**
     * Gets lieuDelivrance
     *
     * @return string|null
     */
    public function getLieuDelivrance()
    {
        return $this->container['lieuDelivrance'];
    }

    /**
     * Sets lieuDelivrance
     *
     * @param string|null $lieuDelivrance lieuDelivrance
     *
     * @return self
     */
    public function setLieuDelivrance($lieuDelivrance)
    {
        if (is_null($lieuDelivrance)) {
            throw new \InvalidArgumentException('non-nullable lieuDelivrance cannot be null');
        }
        if ((mb_strlen($lieuDelivrance) > 100)) {
            throw new \InvalidArgumentException('invalid length for $lieuDelivrance when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($lieuDelivrance) < 0)) {
            throw new \InvalidArgumentException('invalid length for $lieuDelivrance when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-,]*$/", ObjectSerializer::toString($lieuDelivrance)))) {
            throw new \InvalidArgumentException("invalid value for \$lieuDelivrance when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-,]*$/.");
        }

        $this->container['lieuDelivrance'] = $lieuDelivrance;

        return $this;
    }

    /**
     * Gets autorite
     *
     * @return string|null
     */
    public function getAutorite()
    {
        return $this->container['autorite'];
    }

    /**
     * Sets autorite
     *
     * @param string|null $autorite autorite
     *
     * @return self
     */
    public function setAutorite($autorite)
    {
        if (is_null($autorite)) {
            throw new \InvalidArgumentException('non-nullable autorite cannot be null');
        }
        if ((mb_strlen($autorite) > 100)) {
            throw new \InvalidArgumentException('invalid length for $autorite when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($autorite) < 0)) {
            throw new \InvalidArgumentException('invalid length for $autorite when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]*$/", ObjectSerializer::toString($autorite)))) {
            throw new \InvalidArgumentException("invalid value for \$autorite when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]*$/.");
        }

        $this->container['autorite'] = $autorite;

        return $this;
    }

    /**
     * Gets photoPieceIdentiteRecto
     *
     * @return string|null
     */
    public function getPhotoPieceIdentiteRecto()
    {
        return $this->container['photoPieceIdentiteRecto'];
    }

    /**
     * Sets photoPieceIdentiteRecto
     *
     * @param string|null $photoPieceIdentiteRecto photoPieceIdentiteRecto
     *
     * @return self
     */
    public function setPhotoPieceIdentiteRecto($photoPieceIdentiteRecto)
    {
        if (is_null($photoPieceIdentiteRecto)) {
            throw new \InvalidArgumentException('non-nullable photoPieceIdentiteRecto cannot be null');
        }
        $this->container['photoPieceIdentiteRecto'] = $photoPieceIdentiteRecto;

        return $this;
    }

    /**
     * Gets photoPieceIdentiteVerso
     *
     * @return string|null
     */
    public function getPhotoPieceIdentiteVerso()
    {
        return $this->container['photoPieceIdentiteVerso'];
    }

    /**
     * Sets photoPieceIdentiteVerso
     *
     * @param string|null $photoPieceIdentiteVerso photoPieceIdentiteVerso
     *
     * @return self
     */
    public function setPhotoPieceIdentiteVerso($photoPieceIdentiteVerso)
    {
        if (is_null($photoPieceIdentiteVerso)) {
            throw new \InvalidArgumentException('non-nullable photoPieceIdentiteVerso cannot be null');
        }
        $this->container['photoPieceIdentiteVerso'] = $photoPieceIdentiteVerso;

        return $this;
    }

    /**
     * Gets photoIdentite
     *
     * @return string|null
     */
    public function getPhotoIdentite()
    {
        return $this->container['photoIdentite'];
    }

    /**
     * Sets photoIdentite
     *
     * @param string|null $photoIdentite photoIdentite
     *
     * @return self
     */
    public function setPhotoIdentite($photoIdentite)
    {
        if (is_null($photoIdentite)) {
            throw new \InvalidArgumentException('non-nullable photoIdentite cannot be null');
        }
        $this->container['photoIdentite'] = $photoIdentite;

        return $this;
    }

    /**
     * Gets requestId
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string $requestId requestId
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }
        if ((mb_strlen($requestId) > 100)) {
            throw new \InvalidArgumentException('invalid length for $requestId when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($requestId) < 4)) {
            throw new \InvalidArgumentException('invalid length for $requestId when calling PartenaireToCashDtoV2., must be bigger than or equal to 4.');
        }
        if ((!preg_match("/^[a-zA-Z0-9_\\-]{4,100}$/", ObjectSerializer::toString($requestId)))) {
            throw new \InvalidArgumentException("invalid value for \$requestId when calling PartenaireToCashDtoV2., must conform to the pattern /^[a-zA-Z0-9_\\-]{4,100}$/.");
        }

        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets fraisInclus
     *
     * @return bool
     */
    public function getFraisInclus()
    {
        return $this->container['fraisInclus'];
    }

    /**
     * Sets fraisInclus
     *
     * @param bool $fraisInclus fraisInclus
     *
     * @return self
     */
    public function setFraisInclus($fraisInclus)
    {
        if (is_null($fraisInclus)) {
            throw new \InvalidArgumentException('non-nullable fraisInclus cannot be null');
        }
        $this->container['fraisInclus'] = $fraisInclus;

        return $this;
    }

    /**
     * Gets montant
     *
     * @return float
     */
    public function getMontant()
    {
        return $this->container['montant'];
    }

    /**
     * Sets montant
     *
     * @param float $montant montant
     *
     * @return self
     */
    public function setMontant($montant)
    {
        if (is_null($montant)) {
            throw new \InvalidArgumentException('non-nullable montant cannot be null');
        }

        if (($montant > 100000000)) {
            throw new \InvalidArgumentException('invalid value for $montant when calling PartenaireToCashDtoV2., must be smaller than or equal to 100000000.');
        }

        $this->container['montant'] = $montant;

        return $this;
    }

    /**
     * Gets villeDestination
     *
     * @return string
     */
    public function getVilleDestination()
    {
        return $this->container['villeDestination'];
    }

    /**
     * Sets villeDestination
     *
     * @param string $villeDestination villeDestination
     *
     * @return self
     */
    public function setVilleDestination($villeDestination)
    {
        if (is_null($villeDestination)) {
            throw new \InvalidArgumentException('non-nullable villeDestination cannot be null');
        }
        if ((mb_strlen($villeDestination) > 100)) {
            throw new \InvalidArgumentException('invalid length for $villeDestination when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($villeDestination) < 0)) {
            throw new \InvalidArgumentException('invalid length for $villeDestination when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", ObjectSerializer::toString($villeDestination)))) {
            throw new \InvalidArgumentException("invalid value for \$villeDestination when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.");
        }

        $this->container['villeDestination'] = $villeDestination;

        return $this;
    }

    /**
     * Gets nomDestinataire
     *
     * @return string
     */
    public function getNomDestinataire()
    {
        return $this->container['nomDestinataire'];
    }

    /**
     * Sets nomDestinataire
     *
     * @param string $nomDestinataire nomDestinataire
     *
     * @return self
     */
    public function setNomDestinataire($nomDestinataire)
    {
        if (is_null($nomDestinataire)) {
            throw new \InvalidArgumentException('non-nullable nomDestinataire cannot be null');
        }
        if ((mb_strlen($nomDestinataire) > 100)) {
            throw new \InvalidArgumentException('invalid length for $nomDestinataire when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($nomDestinataire) < 0)) {
            throw new \InvalidArgumentException('invalid length for $nomDestinataire when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", ObjectSerializer::toString($nomDestinataire)))) {
            throw new \InvalidArgumentException("invalid value for \$nomDestinataire when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.");
        }

        $this->container['nomDestinataire'] = $nomDestinataire;

        return $this;
    }

    /**
     * Gets prenomDestinataire
     *
     * @return string
     */
    public function getPrenomDestinataire()
    {
        return $this->container['prenomDestinataire'];
    }

    /**
     * Sets prenomDestinataire
     *
     * @param string $prenomDestinataire prenomDestinataire
     *
     * @return self
     */
    public function setPrenomDestinataire($prenomDestinataire)
    {
        if (is_null($prenomDestinataire)) {
            throw new \InvalidArgumentException('non-nullable prenomDestinataire cannot be null');
        }
        if ((mb_strlen($prenomDestinataire) > 100)) {
            throw new \InvalidArgumentException('invalid length for $prenomDestinataire when calling PartenaireToCashDtoV2., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($prenomDestinataire) < 0)) {
            throw new \InvalidArgumentException('invalid length for $prenomDestinataire when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^[\\p{L}\\s'.\\-]{1,100}$/", ObjectSerializer::toString($prenomDestinataire)))) {
            throw new \InvalidArgumentException("invalid value for \$prenomDestinataire when calling PartenaireToCashDtoV2., must conform to the pattern /^[\\p{L}\\s'.\\-]{1,100}$/.");
        }

        $this->container['prenomDestinataire'] = $prenomDestinataire;

        return $this;
    }

    /**
     * Gets indicatifDestinataire
     *
     * @return string
     */
    public function getIndicatifDestinataire()
    {
        return $this->container['indicatifDestinataire'];
    }

    /**
     * Sets indicatifDestinataire
     *
     * @param string $indicatifDestinataire indicatifDestinataire
     *
     * @return self
     */
    public function setIndicatifDestinataire($indicatifDestinataire)
    {
        if (is_null($indicatifDestinataire)) {
            throw new \InvalidArgumentException('non-nullable indicatifDestinataire cannot be null');
        }

        if ((mb_strlen($indicatifDestinataire) < 1)) {
            throw new \InvalidArgumentException('invalid length for $indicatifDestinataire when calling PartenaireToCashDtoV2., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d{2,6}$/", ObjectSerializer::toString($indicatifDestinataire)))) {
            throw new \InvalidArgumentException("invalid value for \$indicatifDestinataire when calling PartenaireToCashDtoV2., must conform to the pattern /^\\d{2,6}$/.");
        }

        $this->container['indicatifDestinataire'] = $indicatifDestinataire;

        return $this;
    }

    /**
     * Gets numeroDestinataire
     *
     * @return string
     */
    public function getNumeroDestinataire()
    {
        return $this->container['numeroDestinataire'];
    }

    /**
     * Sets numeroDestinataire
     *
     * @param string $numeroDestinataire numeroDestinataire
     *
     * @return self
     */
    public function setNumeroDestinataire($numeroDestinataire)
    {
        if (is_null($numeroDestinataire)) {
            throw new \InvalidArgumentException('non-nullable numeroDestinataire cannot be null');
        }

        if ((mb_strlen($numeroDestinataire) < 1)) {
            throw new \InvalidArgumentException('invalid length for $numeroDestinataire when calling PartenaireToCashDtoV2., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\\d{4,15}$/", ObjectSerializer::toString($numeroDestinataire)))) {
            throw new \InvalidArgumentException("invalid value for \$numeroDestinataire when calling PartenaireToCashDtoV2., must conform to the pattern /^\\d{4,15}$/.");
        }

        $this->container['numeroDestinataire'] = $numeroDestinataire;

        return $this;
    }

    /**
     * Gets motifTransaction
     *
     * @return string|null
     */
    public function getMotifTransaction()
    {
        return $this->container['motifTransaction'];
    }

    /**
     * Sets motifTransaction
     *
     * @param string|null $motifTransaction motifTransaction
     *
     * @return self
     */
    public function setMotifTransaction($motifTransaction)
    {
        if (is_null($motifTransaction)) {
            throw new \InvalidArgumentException('non-nullable motifTransaction cannot be null');
        }
        if ((mb_strlen($motifTransaction) > 500)) {
            throw new \InvalidArgumentException('invalid length for $motifTransaction when calling PartenaireToCashDtoV2., must be smaller than or equal to 500.');
        }
        if ((mb_strlen($motifTransaction) < 0)) {
            throw new \InvalidArgumentException('invalid length for $motifTransaction when calling PartenaireToCashDtoV2., must be bigger than or equal to 0.');
        }

        $this->container['motifTransaction'] = $motifTransaction;

        return $this;
    }

    /**
     * Gets adresseIp
     *
     * @return string|null
     */
    public function getAdresseIp()
    {
        return $this->container['adresseIp'];
    }

    /**
     * Sets adresseIp
     *
     * @param string|null $adresseIp adresseIp
     *
     * @return self
     */
    public function setAdresseIp($adresseIp)
    {
        if (is_null($adresseIp)) {
            throw new \InvalidArgumentException('non-nullable adresseIp cannot be null');
        }

        if ((!preg_match("/^((\\d{1,3}\\.){3}\\d{1,3}|[0-9a-fA-F:]{3,39})?$/", ObjectSerializer::toString($adresseIp)))) {
            throw new \InvalidArgumentException("invalid value for \$adresseIp when calling PartenaireToCashDtoV2., must conform to the pattern /^((\\d{1,3}\\.){3}\\d{1,3}|[0-9a-fA-F:]{3,39})?$/.");
        }

        $this->container['adresseIp'] = $adresseIp;

        return $this;
    }

    /**
     * Gets urlCallback
     *
     * @return string|null
     */
    public function getUrlCallback()
    {
        return $this->container['urlCallback'];
    }

    /**
     * Sets urlCallback
     *
     * @param string|null $urlCallback urlCallback
     *
     * @return self
     */
    public function setUrlCallback($urlCallback)
    {
        if (is_null($urlCallback)) {
            throw new \InvalidArgumentException('non-nullable urlCallback cannot be null');
        }
        $this->container['urlCallback'] = $urlCallback;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


