<?php
/**
 * PartenaireToWalletModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * PartenaireToWalletModel Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PartenaireToWalletModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PartenaireToWalletModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'phoneClient' => 'string',
        'montantTransaction' => 'float',
        'longTransaction' => 'string',
        'latTransaction' => 'string',
        'motifTransaction' => 'string',
        'requestId' => 'string',
        'adresseIp' => 'string',
        'phoneDeposant' => 'string',
        'nomDeposant' => 'string',
        'prenomDeposant' => 'string',
        'typePieceDeposant' => 'string',
        'numeroPieceDeposant' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'phoneClient' => null,
        'montantTransaction' => 'double',
        'longTransaction' => null,
        'latTransaction' => null,
        'motifTransaction' => null,
        'requestId' => null,
        'adresseIp' => null,
        'phoneDeposant' => null,
        'nomDeposant' => null,
        'prenomDeposant' => null,
        'typePieceDeposant' => null,
        'numeroPieceDeposant' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'phoneClient' => false,
        'montantTransaction' => false,
        'longTransaction' => false,
        'latTransaction' => false,
        'motifTransaction' => false,
        'requestId' => false,
        'adresseIp' => false,
        'phoneDeposant' => false,
        'nomDeposant' => false,
        'prenomDeposant' => false,
        'typePieceDeposant' => false,
        'numeroPieceDeposant' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'phoneClient' => 'phoneClient',
        'montantTransaction' => 'montantTransaction',
        'longTransaction' => 'longTransaction',
        'latTransaction' => 'latTransaction',
        'motifTransaction' => 'motifTransaction',
        'requestId' => 'requestId',
        'adresseIp' => 'adresseIp',
        'phoneDeposant' => 'phoneDeposant',
        'nomDeposant' => 'nomDeposant',
        'prenomDeposant' => 'prenomDeposant',
        'typePieceDeposant' => 'typePieceDeposant',
        'numeroPieceDeposant' => 'numeroPieceDeposant'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'phoneClient' => 'setPhoneClient',
        'montantTransaction' => 'setMontantTransaction',
        'longTransaction' => 'setLongTransaction',
        'latTransaction' => 'setLatTransaction',
        'motifTransaction' => 'setMotifTransaction',
        'requestId' => 'setRequestId',
        'adresseIp' => 'setAdresseIp',
        'phoneDeposant' => 'setPhoneDeposant',
        'nomDeposant' => 'setNomDeposant',
        'prenomDeposant' => 'setPrenomDeposant',
        'typePieceDeposant' => 'setTypePieceDeposant',
        'numeroPieceDeposant' => 'setNumeroPieceDeposant'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'phoneClient' => 'getPhoneClient',
        'montantTransaction' => 'getMontantTransaction',
        'longTransaction' => 'getLongTransaction',
        'latTransaction' => 'getLatTransaction',
        'motifTransaction' => 'getMotifTransaction',
        'requestId' => 'getRequestId',
        'adresseIp' => 'getAdresseIp',
        'phoneDeposant' => 'getPhoneDeposant',
        'nomDeposant' => 'getNomDeposant',
        'prenomDeposant' => 'getPrenomDeposant',
        'typePieceDeposant' => 'getTypePieceDeposant',
        'numeroPieceDeposant' => 'getNumeroPieceDeposant'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('phoneClient', $data ?? [], null);
        $this->setIfExists('montantTransaction', $data ?? [], null);
        $this->setIfExists('longTransaction', $data ?? [], null);
        $this->setIfExists('latTransaction', $data ?? [], null);
        $this->setIfExists('motifTransaction', $data ?? [], null);
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('adresseIp', $data ?? [], null);
        $this->setIfExists('phoneDeposant', $data ?? [], null);
        $this->setIfExists('nomDeposant', $data ?? [], null);
        $this->setIfExists('prenomDeposant', $data ?? [], null);
        $this->setIfExists('typePieceDeposant', $data ?? [], null);
        $this->setIfExists('numeroPieceDeposant', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets phoneClient
     *
     * @return string|null
     */
    public function getPhoneClient()
    {
        return $this->container['phoneClient'];
    }

    /**
     * Sets phoneClient
     *
     * @param string|null $phoneClient phoneClient
     *
     * @return self
     */
    public function setPhoneClient($phoneClient)
    {
        if (is_null($phoneClient)) {
            throw new \InvalidArgumentException('non-nullable phoneClient cannot be null');
        }
        $this->container['phoneClient'] = $phoneClient;

        return $this;
    }

    /**
     * Gets montantTransaction
     *
     * @return float|null
     */
    public function getMontantTransaction()
    {
        return $this->container['montantTransaction'];
    }

    /**
     * Sets montantTransaction
     *
     * @param float|null $montantTransaction montantTransaction
     *
     * @return self
     */
    public function setMontantTransaction($montantTransaction)
    {
        if (is_null($montantTransaction)) {
            throw new \InvalidArgumentException('non-nullable montantTransaction cannot be null');
        }
        $this->container['montantTransaction'] = $montantTransaction;

        return $this;
    }

    /**
     * Gets longTransaction
     *
     * @return string|null
     */
    public function getLongTransaction()
    {
        return $this->container['longTransaction'];
    }

    /**
     * Sets longTransaction
     *
     * @param string|null $longTransaction longTransaction
     *
     * @return self
     */
    public function setLongTransaction($longTransaction)
    {
        if (is_null($longTransaction)) {
            throw new \InvalidArgumentException('non-nullable longTransaction cannot be null');
        }
        $this->container['longTransaction'] = $longTransaction;

        return $this;
    }

    /**
     * Gets latTransaction
     *
     * @return string|null
     */
    public function getLatTransaction()
    {
        return $this->container['latTransaction'];
    }

    /**
     * Sets latTransaction
     *
     * @param string|null $latTransaction latTransaction
     *
     * @return self
     */
    public function setLatTransaction($latTransaction)
    {
        if (is_null($latTransaction)) {
            throw new \InvalidArgumentException('non-nullable latTransaction cannot be null');
        }
        $this->container['latTransaction'] = $latTransaction;

        return $this;
    }

    /**
     * Gets motifTransaction
     *
     * @return string|null
     */
    public function getMotifTransaction()
    {
        return $this->container['motifTransaction'];
    }

    /**
     * Sets motifTransaction
     *
     * @param string|null $motifTransaction motifTransaction
     *
     * @return self
     */
    public function setMotifTransaction($motifTransaction)
    {
        if (is_null($motifTransaction)) {
            throw new \InvalidArgumentException('non-nullable motifTransaction cannot be null');
        }
        $this->container['motifTransaction'] = $motifTransaction;

        return $this;
    }

    /**
     * Gets requestId
     *
     * @return string|null
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string|null $requestId requestId
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }
        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets adresseIp
     *
     * @return string|null
     */
    public function getAdresseIp()
    {
        return $this->container['adresseIp'];
    }

    /**
     * Sets adresseIp
     *
     * @param string|null $adresseIp adresseIp
     *
     * @return self
     */
    public function setAdresseIp($adresseIp)
    {
        if (is_null($adresseIp)) {
            throw new \InvalidArgumentException('non-nullable adresseIp cannot be null');
        }
        $this->container['adresseIp'] = $adresseIp;

        return $this;
    }

    /**
     * Gets phoneDeposant
     *
     * @return string|null
     */
    public function getPhoneDeposant()
    {
        return $this->container['phoneDeposant'];
    }

    /**
     * Sets phoneDeposant
     *
     * @param string|null $phoneDeposant phoneDeposant
     *
     * @return self
     */
    public function setPhoneDeposant($phoneDeposant)
    {
        if (is_null($phoneDeposant)) {
            throw new \InvalidArgumentException('non-nullable phoneDeposant cannot be null');
        }
        $this->container['phoneDeposant'] = $phoneDeposant;

        return $this;
    }

    /**
     * Gets nomDeposant
     *
     * @return string|null
     */
    public function getNomDeposant()
    {
        return $this->container['nomDeposant'];
    }

    /**
     * Sets nomDeposant
     *
     * @param string|null $nomDeposant nomDeposant
     *
     * @return self
     */
    public function setNomDeposant($nomDeposant)
    {
        if (is_null($nomDeposant)) {
            throw new \InvalidArgumentException('non-nullable nomDeposant cannot be null');
        }
        $this->container['nomDeposant'] = $nomDeposant;

        return $this;
    }

    /**
     * Gets prenomDeposant
     *
     * @return string|null
     */
    public function getPrenomDeposant()
    {
        return $this->container['prenomDeposant'];
    }

    /**
     * Sets prenomDeposant
     *
     * @param string|null $prenomDeposant prenomDeposant
     *
     * @return self
     */
    public function setPrenomDeposant($prenomDeposant)
    {
        if (is_null($prenomDeposant)) {
            throw new \InvalidArgumentException('non-nullable prenomDeposant cannot be null');
        }
        $this->container['prenomDeposant'] = $prenomDeposant;

        return $this;
    }

    /**
     * Gets typePieceDeposant
     *
     * @return string|null
     */
    public function getTypePieceDeposant()
    {
        return $this->container['typePieceDeposant'];
    }

    /**
     * Sets typePieceDeposant
     *
     * @param string|null $typePieceDeposant typePieceDeposant
     *
     * @return self
     */
    public function setTypePieceDeposant($typePieceDeposant)
    {
        if (is_null($typePieceDeposant)) {
            throw new \InvalidArgumentException('non-nullable typePieceDeposant cannot be null');
        }
        $this->container['typePieceDeposant'] = $typePieceDeposant;

        return $this;
    }

    /**
     * Gets numeroPieceDeposant
     *
     * @return string|null
     */
    public function getNumeroPieceDeposant()
    {
        return $this->container['numeroPieceDeposant'];
    }

    /**
     * Sets numeroPieceDeposant
     *
     * @param string|null $numeroPieceDeposant numeroPieceDeposant
     *
     * @return self
     */
    public function setNumeroPieceDeposant($numeroPieceDeposant)
    {
        if (is_null($numeroPieceDeposant)) {
            throw new \InvalidArgumentException('non-nullable numeroPieceDeposant cannot be null');
        }
        $this->container['numeroPieceDeposant'] = $numeroPieceDeposant;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


