<?php
/**
 * PartenaireToWalletResponseV2
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * PartenaireToWalletResponseV2 Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PartenaireToWalletResponseV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PartenaireToWalletResponseV2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'publicId' => 'string',
        'requestId' => 'string',
        'adresseIP' => 'string',
        'reference' => 'string',
        'motif' => 'string',
        'montantRecharge' => 'float',
        'fraisRecharge' => 'float',
        'montantTotalTransaction' => 'float',
        'statusTransaction' => 'string',
        'typeTransaction' => 'string',
        'compteClient' => 'string',
        'nomDeposant' => 'string',
        'prenomDeposant' => 'string',
        'phoneDeposant' => 'string',
        'typePieceDeposant' => 'string',
        'numeroPieceDeposant' => 'string',
        'comptePartenaire' => 'string',
        'nomPartenaire' => 'string',
        'prenomPartenaire' => 'string',
        'dateTransaction' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'publicId' => null,
        'requestId' => null,
        'adresseIP' => null,
        'reference' => null,
        'motif' => null,
        'montantRecharge' => 'double',
        'fraisRecharge' => 'double',
        'montantTotalTransaction' => 'double',
        'statusTransaction' => null,
        'typeTransaction' => null,
        'compteClient' => null,
        'nomDeposant' => null,
        'prenomDeposant' => null,
        'phoneDeposant' => null,
        'typePieceDeposant' => null,
        'numeroPieceDeposant' => null,
        'comptePartenaire' => null,
        'nomPartenaire' => null,
        'prenomPartenaire' => null,
        'dateTransaction' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'publicId' => false,
        'requestId' => false,
        'adresseIP' => false,
        'reference' => false,
        'motif' => false,
        'montantRecharge' => false,
        'fraisRecharge' => false,
        'montantTotalTransaction' => false,
        'statusTransaction' => false,
        'typeTransaction' => false,
        'compteClient' => false,
        'nomDeposant' => false,
        'prenomDeposant' => false,
        'phoneDeposant' => false,
        'typePieceDeposant' => false,
        'numeroPieceDeposant' => false,
        'comptePartenaire' => false,
        'nomPartenaire' => false,
        'prenomPartenaire' => false,
        'dateTransaction' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'publicId' => 'publicId',
        'requestId' => 'requestId',
        'adresseIP' => 'adresseIP',
        'reference' => 'reference',
        'motif' => 'motif',
        'montantRecharge' => 'montantRecharge',
        'fraisRecharge' => 'fraisRecharge',
        'montantTotalTransaction' => 'montantTotalTransaction',
        'statusTransaction' => 'statusTransaction',
        'typeTransaction' => 'typeTransaction',
        'compteClient' => 'compteClient',
        'nomDeposant' => 'nomDeposant',
        'prenomDeposant' => 'prenomDeposant',
        'phoneDeposant' => 'phoneDeposant',
        'typePieceDeposant' => 'typePieceDeposant',
        'numeroPieceDeposant' => 'numeroPieceDeposant',
        'comptePartenaire' => 'ComptePartenaire',
        'nomPartenaire' => 'nomPartenaire',
        'prenomPartenaire' => 'prenomPartenaire',
        'dateTransaction' => 'dateTransaction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'publicId' => 'setPublicId',
        'requestId' => 'setRequestId',
        'adresseIP' => 'setAdresseIP',
        'reference' => 'setReference',
        'motif' => 'setMotif',
        'montantRecharge' => 'setMontantRecharge',
        'fraisRecharge' => 'setFraisRecharge',
        'montantTotalTransaction' => 'setMontantTotalTransaction',
        'statusTransaction' => 'setStatusTransaction',
        'typeTransaction' => 'setTypeTransaction',
        'compteClient' => 'setCompteClient',
        'nomDeposant' => 'setNomDeposant',
        'prenomDeposant' => 'setPrenomDeposant',
        'phoneDeposant' => 'setPhoneDeposant',
        'typePieceDeposant' => 'setTypePieceDeposant',
        'numeroPieceDeposant' => 'setNumeroPieceDeposant',
        'comptePartenaire' => 'setComptePartenaire',
        'nomPartenaire' => 'setNomPartenaire',
        'prenomPartenaire' => 'setPrenomPartenaire',
        'dateTransaction' => 'setDateTransaction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'publicId' => 'getPublicId',
        'requestId' => 'getRequestId',
        'adresseIP' => 'getAdresseIP',
        'reference' => 'getReference',
        'motif' => 'getMotif',
        'montantRecharge' => 'getMontantRecharge',
        'fraisRecharge' => 'getFraisRecharge',
        'montantTotalTransaction' => 'getMontantTotalTransaction',
        'statusTransaction' => 'getStatusTransaction',
        'typeTransaction' => 'getTypeTransaction',
        'compteClient' => 'getCompteClient',
        'nomDeposant' => 'getNomDeposant',
        'prenomDeposant' => 'getPrenomDeposant',
        'phoneDeposant' => 'getPhoneDeposant',
        'typePieceDeposant' => 'getTypePieceDeposant',
        'numeroPieceDeposant' => 'getNumeroPieceDeposant',
        'comptePartenaire' => 'getComptePartenaire',
        'nomPartenaire' => 'getNomPartenaire',
        'prenomPartenaire' => 'getPrenomPartenaire',
        'dateTransaction' => 'getDateTransaction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('publicId', $data ?? [], null);
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('adresseIP', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('motif', $data ?? [], null);
        $this->setIfExists('montantRecharge', $data ?? [], null);
        $this->setIfExists('fraisRecharge', $data ?? [], null);
        $this->setIfExists('montantTotalTransaction', $data ?? [], null);
        $this->setIfExists('statusTransaction', $data ?? [], null);
        $this->setIfExists('typeTransaction', $data ?? [], null);
        $this->setIfExists('compteClient', $data ?? [], null);
        $this->setIfExists('nomDeposant', $data ?? [], null);
        $this->setIfExists('prenomDeposant', $data ?? [], null);
        $this->setIfExists('phoneDeposant', $data ?? [], null);
        $this->setIfExists('typePieceDeposant', $data ?? [], null);
        $this->setIfExists('numeroPieceDeposant', $data ?? [], null);
        $this->setIfExists('comptePartenaire', $data ?? [], null);
        $this->setIfExists('nomPartenaire', $data ?? [], null);
        $this->setIfExists('prenomPartenaire', $data ?? [], null);
        $this->setIfExists('dateTransaction', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets publicId
     *
     * @return string|null
     */
    public function getPublicId()
    {
        return $this->container['publicId'];
    }

    /**
     * Sets publicId
     *
     * @param string|null $publicId publicId
     *
     * @return self
     */
    public function setPublicId($publicId)
    {
        if (is_null($publicId)) {
            throw new \InvalidArgumentException('non-nullable publicId cannot be null');
        }
        $this->container['publicId'] = $publicId;

        return $this;
    }

    /**
     * Gets requestId
     *
     * @return string|null
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string|null $requestId requestId
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }
        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets adresseIP
     *
     * @return string|null
     */
    public function getAdresseIP()
    {
        return $this->container['adresseIP'];
    }

    /**
     * Sets adresseIP
     *
     * @param string|null $adresseIP adresseIP
     *
     * @return self
     */
    public function setAdresseIP($adresseIP)
    {
        if (is_null($adresseIP)) {
            throw new \InvalidArgumentException('non-nullable adresseIP cannot be null');
        }
        $this->container['adresseIP'] = $adresseIP;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference reference
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets motif
     *
     * @return string|null
     */
    public function getMotif()
    {
        return $this->container['motif'];
    }

    /**
     * Sets motif
     *
     * @param string|null $motif motif
     *
     * @return self
     */
    public function setMotif($motif)
    {
        if (is_null($motif)) {
            throw new \InvalidArgumentException('non-nullable motif cannot be null');
        }
        $this->container['motif'] = $motif;

        return $this;
    }

    /**
     * Gets montantRecharge
     *
     * @return float|null
     */
    public function getMontantRecharge()
    {
        return $this->container['montantRecharge'];
    }

    /**
     * Sets montantRecharge
     *
     * @param float|null $montantRecharge montantRecharge
     *
     * @return self
     */
    public function setMontantRecharge($montantRecharge)
    {
        if (is_null($montantRecharge)) {
            throw new \InvalidArgumentException('non-nullable montantRecharge cannot be null');
        }
        $this->container['montantRecharge'] = $montantRecharge;

        return $this;
    }

    /**
     * Gets fraisRecharge
     *
     * @return float|null
     */
    public function getFraisRecharge()
    {
        return $this->container['fraisRecharge'];
    }

    /**
     * Sets fraisRecharge
     *
     * @param float|null $fraisRecharge fraisRecharge
     *
     * @return self
     */
    public function setFraisRecharge($fraisRecharge)
    {
        if (is_null($fraisRecharge)) {
            throw new \InvalidArgumentException('non-nullable fraisRecharge cannot be null');
        }
        $this->container['fraisRecharge'] = $fraisRecharge;

        return $this;
    }

    /**
     * Gets montantTotalTransaction
     *
     * @return float|null
     */
    public function getMontantTotalTransaction()
    {
        return $this->container['montantTotalTransaction'];
    }

    /**
     * Sets montantTotalTransaction
     *
     * @param float|null $montantTotalTransaction montantTotalTransaction
     *
     * @return self
     */
    public function setMontantTotalTransaction($montantTotalTransaction)
    {
        if (is_null($montantTotalTransaction)) {
            throw new \InvalidArgumentException('non-nullable montantTotalTransaction cannot be null');
        }
        $this->container['montantTotalTransaction'] = $montantTotalTransaction;

        return $this;
    }

    /**
     * Gets statusTransaction
     *
     * @return string|null
     */
    public function getStatusTransaction()
    {
        return $this->container['statusTransaction'];
    }

    /**
     * Sets statusTransaction
     *
     * @param string|null $statusTransaction statusTransaction
     *
     * @return self
     */
    public function setStatusTransaction($statusTransaction)
    {
        if (is_null($statusTransaction)) {
            throw new \InvalidArgumentException('non-nullable statusTransaction cannot be null');
        }
        $this->container['statusTransaction'] = $statusTransaction;

        return $this;
    }

    /**
     * Gets typeTransaction
     *
     * @return string|null
     */
    public function getTypeTransaction()
    {
        return $this->container['typeTransaction'];
    }

    /**
     * Sets typeTransaction
     *
     * @param string|null $typeTransaction typeTransaction
     *
     * @return self
     */
    public function setTypeTransaction($typeTransaction)
    {
        if (is_null($typeTransaction)) {
            throw new \InvalidArgumentException('non-nullable typeTransaction cannot be null');
        }
        $this->container['typeTransaction'] = $typeTransaction;

        return $this;
    }

    /**
     * Gets compteClient
     *
     * @return string|null
     */
    public function getCompteClient()
    {
        return $this->container['compteClient'];
    }

    /**
     * Sets compteClient
     *
     * @param string|null $compteClient compteClient
     *
     * @return self
     */
    public function setCompteClient($compteClient)
    {
        if (is_null($compteClient)) {
            throw new \InvalidArgumentException('non-nullable compteClient cannot be null');
        }
        $this->container['compteClient'] = $compteClient;

        return $this;
    }

    /**
     * Gets nomDeposant
     *
     * @return string|null
     */
    public function getNomDeposant()
    {
        return $this->container['nomDeposant'];
    }

    /**
     * Sets nomDeposant
     *
     * @param string|null $nomDeposant nomDeposant
     *
     * @return self
     */
    public function setNomDeposant($nomDeposant)
    {
        if (is_null($nomDeposant)) {
            throw new \InvalidArgumentException('non-nullable nomDeposant cannot be null');
        }
        $this->container['nomDeposant'] = $nomDeposant;

        return $this;
    }

    /**
     * Gets prenomDeposant
     *
     * @return string|null
     */
    public function getPrenomDeposant()
    {
        return $this->container['prenomDeposant'];
    }

    /**
     * Sets prenomDeposant
     *
     * @param string|null $prenomDeposant prenomDeposant
     *
     * @return self
     */
    public function setPrenomDeposant($prenomDeposant)
    {
        if (is_null($prenomDeposant)) {
            throw new \InvalidArgumentException('non-nullable prenomDeposant cannot be null');
        }
        $this->container['prenomDeposant'] = $prenomDeposant;

        return $this;
    }

    /**
     * Gets phoneDeposant
     *
     * @return string|null
     */
    public function getPhoneDeposant()
    {
        return $this->container['phoneDeposant'];
    }

    /**
     * Sets phoneDeposant
     *
     * @param string|null $phoneDeposant phoneDeposant
     *
     * @return self
     */
    public function setPhoneDeposant($phoneDeposant)
    {
        if (is_null($phoneDeposant)) {
            throw new \InvalidArgumentException('non-nullable phoneDeposant cannot be null');
        }
        $this->container['phoneDeposant'] = $phoneDeposant;

        return $this;
    }

    /**
     * Gets typePieceDeposant
     *
     * @return string|null
     */
    public function getTypePieceDeposant()
    {
        return $this->container['typePieceDeposant'];
    }

    /**
     * Sets typePieceDeposant
     *
     * @param string|null $typePieceDeposant typePieceDeposant
     *
     * @return self
     */
    public function setTypePieceDeposant($typePieceDeposant)
    {
        if (is_null($typePieceDeposant)) {
            throw new \InvalidArgumentException('non-nullable typePieceDeposant cannot be null');
        }
        $this->container['typePieceDeposant'] = $typePieceDeposant;

        return $this;
    }

    /**
     * Gets numeroPieceDeposant
     *
     * @return string|null
     */
    public function getNumeroPieceDeposant()
    {
        return $this->container['numeroPieceDeposant'];
    }

    /**
     * Sets numeroPieceDeposant
     *
     * @param string|null $numeroPieceDeposant numeroPieceDeposant
     *
     * @return self
     */
    public function setNumeroPieceDeposant($numeroPieceDeposant)
    {
        if (is_null($numeroPieceDeposant)) {
            throw new \InvalidArgumentException('non-nullable numeroPieceDeposant cannot be null');
        }
        $this->container['numeroPieceDeposant'] = $numeroPieceDeposant;

        return $this;
    }

    /**
     * Gets comptePartenaire
     *
     * @return string|null
     */
    public function getComptePartenaire()
    {
        return $this->container['comptePartenaire'];
    }

    /**
     * Sets comptePartenaire
     *
     * @param string|null $comptePartenaire comptePartenaire
     *
     * @return self
     */
    public function setComptePartenaire($comptePartenaire)
    {
        if (is_null($comptePartenaire)) {
            throw new \InvalidArgumentException('non-nullable comptePartenaire cannot be null');
        }
        $this->container['comptePartenaire'] = $comptePartenaire;

        return $this;
    }

    /**
     * Gets nomPartenaire
     *
     * @return string|null
     */
    public function getNomPartenaire()
    {
        return $this->container['nomPartenaire'];
    }

    /**
     * Sets nomPartenaire
     *
     * @param string|null $nomPartenaire nomPartenaire
     *
     * @return self
     */
    public function setNomPartenaire($nomPartenaire)
    {
        if (is_null($nomPartenaire)) {
            throw new \InvalidArgumentException('non-nullable nomPartenaire cannot be null');
        }
        $this->container['nomPartenaire'] = $nomPartenaire;

        return $this;
    }

    /**
     * Gets prenomPartenaire
     *
     * @return string|null
     */
    public function getPrenomPartenaire()
    {
        return $this->container['prenomPartenaire'];
    }

    /**
     * Sets prenomPartenaire
     *
     * @param string|null $prenomPartenaire prenomPartenaire
     *
     * @return self
     */
    public function setPrenomPartenaire($prenomPartenaire)
    {
        if (is_null($prenomPartenaire)) {
            throw new \InvalidArgumentException('non-nullable prenomPartenaire cannot be null');
        }
        $this->container['prenomPartenaire'] = $prenomPartenaire;

        return $this;
    }

    /**
     * Gets dateTransaction
     *
     * @return \DateTime|null
     */
    public function getDateTransaction()
    {
        return $this->container['dateTransaction'];
    }

    /**
     * Sets dateTransaction
     *
     * @param \DateTime|null $dateTransaction dateTransaction
     *
     * @return self
     */
    public function setDateTransaction($dateTransaction)
    {
        if (is_null($dateTransaction)) {
            throw new \InvalidArgumentException('non-nullable dateTransaction cannot be null');
        }
        $this->container['dateTransaction'] = $dateTransaction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


