<?php
/**
 * TransactionResponseV2
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nita\Sdk\Model;

use \ArrayAccess;
use \Nita\Sdk\ObjectSerializer;

/**
 * TransactionResponseV2 Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransactionResponseV2 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TransactionResponseV2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'publicId' => 'string',
        'requestId' => 'string',
        'codeEnvoi' => 'string',
        'montant' => 'float',
        'fraisEnvoi' => 'float',
        'reduction' => 'float',
        'fraisInclus' => 'bool',
        'total' => 'float',
        'statusTransaction' => 'string',
        'typeTransaction' => 'string',
        'typeOperation' => 'string',
        'nomExpediteur' => 'string',
        'prenomExpediteur' => 'string',
        'telephoneExpediteur' => 'string',
        'nomDestinataire' => 'string',
        'prenomDestinataire' => 'string',
        'telephoneDestinataire' => 'string',
        'villeDestinataire' => 'string',
        'paysDestinataire' => 'string',
        'dateTransaction' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'publicId' => null,
        'requestId' => null,
        'codeEnvoi' => null,
        'montant' => 'double',
        'fraisEnvoi' => 'double',
        'reduction' => 'double',
        'fraisInclus' => null,
        'total' => 'double',
        'statusTransaction' => null,
        'typeTransaction' => null,
        'typeOperation' => null,
        'nomExpediteur' => null,
        'prenomExpediteur' => null,
        'telephoneExpediteur' => null,
        'nomDestinataire' => null,
        'prenomDestinataire' => null,
        'telephoneDestinataire' => null,
        'villeDestinataire' => null,
        'paysDestinataire' => null,
        'dateTransaction' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'publicId' => false,
        'requestId' => false,
        'codeEnvoi' => false,
        'montant' => false,
        'fraisEnvoi' => false,
        'reduction' => false,
        'fraisInclus' => false,
        'total' => false,
        'statusTransaction' => false,
        'typeTransaction' => false,
        'typeOperation' => false,
        'nomExpediteur' => false,
        'prenomExpediteur' => false,
        'telephoneExpediteur' => false,
        'nomDestinataire' => false,
        'prenomDestinataire' => false,
        'telephoneDestinataire' => false,
        'villeDestinataire' => false,
        'paysDestinataire' => false,
        'dateTransaction' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'publicId' => 'publicId',
        'requestId' => 'requestId',
        'codeEnvoi' => 'codeEnvoi',
        'montant' => 'montant',
        'fraisEnvoi' => 'fraisEnvoi',
        'reduction' => 'reduction',
        'fraisInclus' => 'fraisInclus',
        'total' => 'total',
        'statusTransaction' => 'statusTransaction',
        'typeTransaction' => 'typeTransaction',
        'typeOperation' => 'typeOperation',
        'nomExpediteur' => 'nomExpediteur',
        'prenomExpediteur' => 'prenomExpediteur',
        'telephoneExpediteur' => 'telephoneExpediteur',
        'nomDestinataire' => 'nomDestinataire',
        'prenomDestinataire' => 'prenomDestinataire',
        'telephoneDestinataire' => 'telephoneDestinataire',
        'villeDestinataire' => 'villeDestinataire',
        'paysDestinataire' => 'paysDestinataire',
        'dateTransaction' => 'dateTransaction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'publicId' => 'setPublicId',
        'requestId' => 'setRequestId',
        'codeEnvoi' => 'setCodeEnvoi',
        'montant' => 'setMontant',
        'fraisEnvoi' => 'setFraisEnvoi',
        'reduction' => 'setReduction',
        'fraisInclus' => 'setFraisInclus',
        'total' => 'setTotal',
        'statusTransaction' => 'setStatusTransaction',
        'typeTransaction' => 'setTypeTransaction',
        'typeOperation' => 'setTypeOperation',
        'nomExpediteur' => 'setNomExpediteur',
        'prenomExpediteur' => 'setPrenomExpediteur',
        'telephoneExpediteur' => 'setTelephoneExpediteur',
        'nomDestinataire' => 'setNomDestinataire',
        'prenomDestinataire' => 'setPrenomDestinataire',
        'telephoneDestinataire' => 'setTelephoneDestinataire',
        'villeDestinataire' => 'setVilleDestinataire',
        'paysDestinataire' => 'setPaysDestinataire',
        'dateTransaction' => 'setDateTransaction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'publicId' => 'getPublicId',
        'requestId' => 'getRequestId',
        'codeEnvoi' => 'getCodeEnvoi',
        'montant' => 'getMontant',
        'fraisEnvoi' => 'getFraisEnvoi',
        'reduction' => 'getReduction',
        'fraisInclus' => 'getFraisInclus',
        'total' => 'getTotal',
        'statusTransaction' => 'getStatusTransaction',
        'typeTransaction' => 'getTypeTransaction',
        'typeOperation' => 'getTypeOperation',
        'nomExpediteur' => 'getNomExpediteur',
        'prenomExpediteur' => 'getPrenomExpediteur',
        'telephoneExpediteur' => 'getTelephoneExpediteur',
        'nomDestinataire' => 'getNomDestinataire',
        'prenomDestinataire' => 'getPrenomDestinataire',
        'telephoneDestinataire' => 'getTelephoneDestinataire',
        'villeDestinataire' => 'getVilleDestinataire',
        'paysDestinataire' => 'getPaysDestinataire',
        'dateTransaction' => 'getDateTransaction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('publicId', $data ?? [], null);
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('codeEnvoi', $data ?? [], null);
        $this->setIfExists('montant', $data ?? [], null);
        $this->setIfExists('fraisEnvoi', $data ?? [], null);
        $this->setIfExists('reduction', $data ?? [], null);
        $this->setIfExists('fraisInclus', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('statusTransaction', $data ?? [], null);
        $this->setIfExists('typeTransaction', $data ?? [], null);
        $this->setIfExists('typeOperation', $data ?? [], null);
        $this->setIfExists('nomExpediteur', $data ?? [], null);
        $this->setIfExists('prenomExpediteur', $data ?? [], null);
        $this->setIfExists('telephoneExpediteur', $data ?? [], null);
        $this->setIfExists('nomDestinataire', $data ?? [], null);
        $this->setIfExists('prenomDestinataire', $data ?? [], null);
        $this->setIfExists('telephoneDestinataire', $data ?? [], null);
        $this->setIfExists('villeDestinataire', $data ?? [], null);
        $this->setIfExists('paysDestinataire', $data ?? [], null);
        $this->setIfExists('dateTransaction', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets publicId
     *
     * @return string|null
     */
    public function getPublicId()
    {
        return $this->container['publicId'];
    }

    /**
     * Sets publicId
     *
     * @param string|null $publicId publicId
     *
     * @return self
     */
    public function setPublicId($publicId)
    {
        if (is_null($publicId)) {
            throw new \InvalidArgumentException('non-nullable publicId cannot be null');
        }
        $this->container['publicId'] = $publicId;

        return $this;
    }

    /**
     * Gets requestId
     *
     * @return string|null
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string|null $requestId requestId
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }
        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets codeEnvoi
     *
     * @return string|null
     */
    public function getCodeEnvoi()
    {
        return $this->container['codeEnvoi'];
    }

    /**
     * Sets codeEnvoi
     *
     * @param string|null $codeEnvoi codeEnvoi
     *
     * @return self
     */
    public function setCodeEnvoi($codeEnvoi)
    {
        if (is_null($codeEnvoi)) {
            throw new \InvalidArgumentException('non-nullable codeEnvoi cannot be null');
        }
        $this->container['codeEnvoi'] = $codeEnvoi;

        return $this;
    }

    /**
     * Gets montant
     *
     * @return float|null
     */
    public function getMontant()
    {
        return $this->container['montant'];
    }

    /**
     * Sets montant
     *
     * @param float|null $montant montant
     *
     * @return self
     */
    public function setMontant($montant)
    {
        if (is_null($montant)) {
            throw new \InvalidArgumentException('non-nullable montant cannot be null');
        }
        $this->container['montant'] = $montant;

        return $this;
    }

    /**
     * Gets fraisEnvoi
     *
     * @return float|null
     */
    public function getFraisEnvoi()
    {
        return $this->container['fraisEnvoi'];
    }

    /**
     * Sets fraisEnvoi
     *
     * @param float|null $fraisEnvoi fraisEnvoi
     *
     * @return self
     */
    public function setFraisEnvoi($fraisEnvoi)
    {
        if (is_null($fraisEnvoi)) {
            throw new \InvalidArgumentException('non-nullable fraisEnvoi cannot be null');
        }
        $this->container['fraisEnvoi'] = $fraisEnvoi;

        return $this;
    }

    /**
     * Gets reduction
     *
     * @return float|null
     */
    public function getReduction()
    {
        return $this->container['reduction'];
    }

    /**
     * Sets reduction
     *
     * @param float|null $reduction reduction
     *
     * @return self
     */
    public function setReduction($reduction)
    {
        if (is_null($reduction)) {
            throw new \InvalidArgumentException('non-nullable reduction cannot be null');
        }
        $this->container['reduction'] = $reduction;

        return $this;
    }

    /**
     * Gets fraisInclus
     *
     * @return bool|null
     */
    public function getFraisInclus()
    {
        return $this->container['fraisInclus'];
    }

    /**
     * Sets fraisInclus
     *
     * @param bool|null $fraisInclus fraisInclus
     *
     * @return self
     */
    public function setFraisInclus($fraisInclus)
    {
        if (is_null($fraisInclus)) {
            throw new \InvalidArgumentException('non-nullable fraisInclus cannot be null');
        }
        $this->container['fraisInclus'] = $fraisInclus;

        return $this;
    }

    /**
     * Gets total
     *
     * @return float|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param float|null $total total
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets statusTransaction
     *
     * @return string|null
     */
    public function getStatusTransaction()
    {
        return $this->container['statusTransaction'];
    }

    /**
     * Sets statusTransaction
     *
     * @param string|null $statusTransaction statusTransaction
     *
     * @return self
     */
    public function setStatusTransaction($statusTransaction)
    {
        if (is_null($statusTransaction)) {
            throw new \InvalidArgumentException('non-nullable statusTransaction cannot be null');
        }
        $this->container['statusTransaction'] = $statusTransaction;

        return $this;
    }

    /**
     * Gets typeTransaction
     *
     * @return string|null
     */
    public function getTypeTransaction()
    {
        return $this->container['typeTransaction'];
    }

    /**
     * Sets typeTransaction
     *
     * @param string|null $typeTransaction typeTransaction
     *
     * @return self
     */
    public function setTypeTransaction($typeTransaction)
    {
        if (is_null($typeTransaction)) {
            throw new \InvalidArgumentException('non-nullable typeTransaction cannot be null');
        }
        $this->container['typeTransaction'] = $typeTransaction;

        return $this;
    }

    /**
     * Gets typeOperation
     *
     * @return string|null
     */
    public function getTypeOperation()
    {
        return $this->container['typeOperation'];
    }

    /**
     * Sets typeOperation
     *
     * @param string|null $typeOperation typeOperation
     *
     * @return self
     */
    public function setTypeOperation($typeOperation)
    {
        if (is_null($typeOperation)) {
            throw new \InvalidArgumentException('non-nullable typeOperation cannot be null');
        }
        $this->container['typeOperation'] = $typeOperation;

        return $this;
    }

    /**
     * Gets nomExpediteur
     *
     * @return string|null
     */
    public function getNomExpediteur()
    {
        return $this->container['nomExpediteur'];
    }

    /**
     * Sets nomExpediteur
     *
     * @param string|null $nomExpediteur nomExpediteur
     *
     * @return self
     */
    public function setNomExpediteur($nomExpediteur)
    {
        if (is_null($nomExpediteur)) {
            throw new \InvalidArgumentException('non-nullable nomExpediteur cannot be null');
        }
        $this->container['nomExpediteur'] = $nomExpediteur;

        return $this;
    }

    /**
     * Gets prenomExpediteur
     *
     * @return string|null
     */
    public function getPrenomExpediteur()
    {
        return $this->container['prenomExpediteur'];
    }

    /**
     * Sets prenomExpediteur
     *
     * @param string|null $prenomExpediteur prenomExpediteur
     *
     * @return self
     */
    public function setPrenomExpediteur($prenomExpediteur)
    {
        if (is_null($prenomExpediteur)) {
            throw new \InvalidArgumentException('non-nullable prenomExpediteur cannot be null');
        }
        $this->container['prenomExpediteur'] = $prenomExpediteur;

        return $this;
    }

    /**
     * Gets telephoneExpediteur
     *
     * @return string|null
     */
    public function getTelephoneExpediteur()
    {
        return $this->container['telephoneExpediteur'];
    }

    /**
     * Sets telephoneExpediteur
     *
     * @param string|null $telephoneExpediteur telephoneExpediteur
     *
     * @return self
     */
    public function setTelephoneExpediteur($telephoneExpediteur)
    {
        if (is_null($telephoneExpediteur)) {
            throw new \InvalidArgumentException('non-nullable telephoneExpediteur cannot be null');
        }
        $this->container['telephoneExpediteur'] = $telephoneExpediteur;

        return $this;
    }

    /**
     * Gets nomDestinataire
     *
     * @return string|null
     */
    public function getNomDestinataire()
    {
        return $this->container['nomDestinataire'];
    }

    /**
     * Sets nomDestinataire
     *
     * @param string|null $nomDestinataire nomDestinataire
     *
     * @return self
     */
    public function setNomDestinataire($nomDestinataire)
    {
        if (is_null($nomDestinataire)) {
            throw new \InvalidArgumentException('non-nullable nomDestinataire cannot be null');
        }
        $this->container['nomDestinataire'] = $nomDestinataire;

        return $this;
    }

    /**
     * Gets prenomDestinataire
     *
     * @return string|null
     */
    public function getPrenomDestinataire()
    {
        return $this->container['prenomDestinataire'];
    }

    /**
     * Sets prenomDestinataire
     *
     * @param string|null $prenomDestinataire prenomDestinataire
     *
     * @return self
     */
    public function setPrenomDestinataire($prenomDestinataire)
    {
        if (is_null($prenomDestinataire)) {
            throw new \InvalidArgumentException('non-nullable prenomDestinataire cannot be null');
        }
        $this->container['prenomDestinataire'] = $prenomDestinataire;

        return $this;
    }

    /**
     * Gets telephoneDestinataire
     *
     * @return string|null
     */
    public function getTelephoneDestinataire()
    {
        return $this->container['telephoneDestinataire'];
    }

    /**
     * Sets telephoneDestinataire
     *
     * @param string|null $telephoneDestinataire telephoneDestinataire
     *
     * @return self
     */
    public function setTelephoneDestinataire($telephoneDestinataire)
    {
        if (is_null($telephoneDestinataire)) {
            throw new \InvalidArgumentException('non-nullable telephoneDestinataire cannot be null');
        }
        $this->container['telephoneDestinataire'] = $telephoneDestinataire;

        return $this;
    }

    /**
     * Gets villeDestinataire
     *
     * @return string|null
     */
    public function getVilleDestinataire()
    {
        return $this->container['villeDestinataire'];
    }

    /**
     * Sets villeDestinataire
     *
     * @param string|null $villeDestinataire villeDestinataire
     *
     * @return self
     */
    public function setVilleDestinataire($villeDestinataire)
    {
        if (is_null($villeDestinataire)) {
            throw new \InvalidArgumentException('non-nullable villeDestinataire cannot be null');
        }
        $this->container['villeDestinataire'] = $villeDestinataire;

        return $this;
    }

    /**
     * Gets paysDestinataire
     *
     * @return string|null
     */
    public function getPaysDestinataire()
    {
        return $this->container['paysDestinataire'];
    }

    /**
     * Sets paysDestinataire
     *
     * @param string|null $paysDestinataire paysDestinataire
     *
     * @return self
     */
    public function setPaysDestinataire($paysDestinataire)
    {
        if (is_null($paysDestinataire)) {
            throw new \InvalidArgumentException('non-nullable paysDestinataire cannot be null');
        }
        $this->container['paysDestinataire'] = $paysDestinataire;

        return $this;
    }

    /**
     * Gets dateTransaction
     *
     * @return \DateTime|null
     */
    public function getDateTransaction()
    {
        return $this->container['dateTransaction'];
    }

    /**
     * Sets dateTransaction
     *
     * @param \DateTime|null $dateTransaction dateTransaction
     *
     * @return self
     */
    public function setDateTransaction($dateTransaction)
    {
        if (is_null($dateTransaction)) {
            throw new \InvalidArgumentException('non-nullable dateTransaction cannot be null');
        }
        $this->container['dateTransaction'] = $dateTransaction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


