<?php
/**
 * ApisResponseV2TransactionResponseV2Test
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nita\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApisResponseV2TransactionResponseV2Test Class Doc Comment
 *
 * @category    Class
 * @description ApisResponseV2TransactionResponseV2
 * @package     Nita\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApisResponseV2TransactionResponseV2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApisResponseV2TransactionResponseV2"
     */
    public function testApisResponseV2TransactionResponseV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
