<?php
/**
 * EnvoiPayableDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * Les APIs du système de transfert de NITA dédié à niger poste
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nita\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EnvoiPayableDtoTest Class Doc Comment
 *
 * @category    Class
 * @description EnvoiPayableDto
 * @package     Nita\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EnvoiPayableDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EnvoiPayableDto"
     */
    public function testEnvoiPayableDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "idEnvoi"
     */
    public function testPropertyIdEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codeEnvoi"
     */
    public function testPropertyCodeEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "villeDestination"
     */
    public function testPropertyVilleDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paysDestination"
     */
    public function testPropertyPaysDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expediteurNom"
     */
    public function testPropertyExpediteurNom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expediteurPrenom"
     */
    public function testPropertyExpediteurPrenom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expediteurTelephone"
     */
    public function testPropertyExpediteurTelephone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinataireNom"
     */
    public function testPropertyDestinataireNom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinatairePrenom"
     */
    public function testPropertyDestinatairePrenom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinataireTelephone"
     */
    public function testPropertyDestinataireTelephone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dateEmission"
     */
    public function testPropertyDateEmission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "montant"
     */
    public function testPropertyMontant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "devise"
     */
    public function testPropertyDevise()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "typeSource"
     */
    public function testPropertyTypeSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
