<?php
/**
 * ModelEditEnvoieRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * Les APIs du système de transfert de NITA dédié à niger poste
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nita\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ModelEditEnvoieRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ModelEditEnvoieRequest
 * @package     Nita\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ModelEditEnvoieRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ModelEditEnvoieRequest"
     */
    public function testModelEditEnvoieRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "villeDestination"
     */
    public function testPropertyVilleDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nomDestinateur"
     */
    public function testPropertyNomDestinateur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "prenomDestinateur"
     */
    public function testPropertyPrenomDestinateur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nomExpediteur"
     */
    public function testPropertyNomExpediteur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "prenomExpediteur"
     */
    public function testPropertyPrenomExpediteur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phoneExpediteur"
     */
    public function testPropertyPhoneExpediteur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phoneDestinateur"
     */
    public function testPropertyPhoneDestinateur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "motifEnvoi"
     */
    public function testPropertyMotifEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codeEnvoi"
     */
    public function testPropertyCodeEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "montantEnvoi"
     */
    public function testPropertyMontantEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fraisEnvoi"
     */
    public function testPropertyFraisEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fraisInclus"
     */
    public function testPropertyFraisInclus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
