<?php
/**
 * PartenaireRetraitDtoV2Test
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * Les APIs du système de transfert de NITA dédié à niger poste
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nita\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PartenaireRetraitDtoV2Test Class Doc Comment
 *
 * @category    Class
 * @description PartenaireRetraitDtoV2
 * @package     Nita\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PartenaireRetraitDtoV2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PartenaireRetraitDtoV2"
     */
    public function testPartenaireRetraitDtoV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codeEnvoi"
     */
    public function testPropertyCodeEnvoi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "searchMode"
     */
    public function testPropertySearchMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "typeRetrait"
     */
    public function testPropertyTypeRetrait()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "typePiece"
     */
    public function testPropertyTypePiece()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numeroPiece"
     */
    public function testPropertyNumeroPiece()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nomRetirant"
     */
    public function testPropertyNomRetirant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "prenomRetirant"
     */
    public function testPropertyPrenomRetirant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phoneRetirant"
     */
    public function testPropertyPhoneRetirant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "typePieceRetirant"
     */
    public function testPropertyTypePieceRetirant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numeroPieceRetirant"
     */
    public function testPropertyNumeroPieceRetirant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "requestId"
     */
    public function testPropertyRequestId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "adresseIp"
     */
    public function testPropertyAdresseIp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
