<?php
/**
 * TransactionsV2ApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nita transfert d'argent | Niger Poste
 *
 * Les APIs du système de transfert de NITA dédié à niger poste
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Nita\Sdk\Test\Api;

use \Nita\Sdk\Configuration;
use \Nita\Sdk\ApiException;
use \Nita\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Nita\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsV2ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for annulePartenaireToWallet
     *
     * Partenaire To Wallet (v2).
     *
     */
    public function testAnnulePartenaireToWallet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for annulerEnvoiMyNita
     *
     * Annuler un envoi MyNita (v2).
     *
     */
    public function testAnnulerEnvoiMyNita()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvoiToEdit
     *
     * Récupérer les informations d'un envoi à éditer (v2).
     *
     */
    public function testGetEnvoiToEdit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPartenaireToWallet
     *
     * Récupération d'une opération Partenaire To Wallet (v2).
     *
     */
    public function testGetPartenaireToWallet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partenaireToCash
     *
     * Envoi Partenaire To Cash (v2).
     *
     */
    public function testPartenaireToCash()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partenaireToWallet
     *
     * Partenaire To Wallet (v2).
     *
     */
    public function testPartenaireToWallet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrait
     *
     * Retrait d'un envoi (v2).
     *
     */
    public function testRetrait()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retraitRechercher
     *
     * Recherche d'envois retirables (v2).
     *
     */
    public function testRetraitRechercher()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEnvoiMyNita
     *
     * Modifier un envoi MyNita (v2).
     *
     */
    public function testUpdateEnvoiMyNita()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
